### ISSUE TITLE
AdapterInterface does not define query as a method

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-db#1]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-db/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-db/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

### Description of what I am trying to accomplish:

- Given the [recommendation here](https://github.com/zendframework/zendframework/issues/3012#issuecomment-73783628) to fall back to manual sql using the adapter in order to accomplish `FOR UPDATE` statements in MariaDb / MySQL environments, one should still be able to inject an interface into their class objects. 
- The `\Zend\Db\Adapter\Adapter` implements no such interface which defines a `query` method

### Code to reproduce the issue

```
class FooBar
{
    /**
     * @var \Zend\Db\Adapter\AdapterInterface
     */
    private $adapter;

    public function  __construct(
        \Zend\Db\Adapter\AdapterInterface $adapter
    ) {
        $this->adapter = $adapter
    }

    public function getRecordById(int $id): \ArrayObject
    {
        /**
         * @var \Zend\Db\ResultSet\ResultSet $resultSet
         */
        $resultSet = $this->adapter->query('SELECT * FROM foo_bar WHERE id = :id FOR UPDATE', ['id' => $id]);
        return $resultSet->current();
    }
}
```

### Expected results

- AdapterInterface should have `query` defined so that it is a known accessible method. This will:
  - Allow for DI replacement in applications that may require such things
  - Allow for mocking of the Interface in order to accomplish unit testing of the class

### Actual results

Since (in my application) `\Zend\Db\Adapter\Adapter` is the concrete class that is injected at run time, the method still works. However this leads to:
  - IDE shows an error as it is not a known method of the interface
  - Inability to properly unit test the class since I cannot call `->query` on a mocked instance of `\Zend\Db\Adapter\AdapterInterface`

---

Originally posted by @dfelton at https://github.com/zendframework/zend-db/issues/398

**Comment by dfelton** [comment]
Thank you @weierophinney 

laminas is a new name to me I was unaware of such changes coming to Zend. I'll be sure to follow and I am interested in seeing where this repo goes.

Have a great new year!

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
