### ISSUE TITLE
Feature/table gateway params

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#100]
ping @weierophinney 
Added optional parameter for selectWith function where you can provid e additional parameters to execute function.
This will allow to user tablegateway features with flexibility of ordinary select

---

Originally posted by @AdamiecRadek at https://github.com/zendframework/zend-db/pull/160

**Comment by michalbundyra** [comment]
@weierophinney - Not directly related to this PR but I would like to know your opinion about this idea.

This PR was created to allow for usage of Table Gateway Features like master/slave with regular Select objects.

Why do those features need to be restricted to TG? Wouldn't it be better to have the option to set up additional features globally for an adapter? 

I know that master/slave feature requires the second adapter but possibly attaching slave adapter to the master is not such a bad idea.

Anyway..... I don't have any solutions to this yet but I this could be done I can start working on PR with those changes.  


---

Originally posted by @AGmakonts at https://github.com/zendframework/zend-db/pull/160#issuecomment-245034174

**Comment by michalbundyra** [comment]
@AdamiecRadek unit tests are missing, can you provide it? Thanks.

---

Originally posted by @ezimuel at https://github.com/zendframework/zend-db/pull/160#issuecomment-285099332

**Comment by michalbundyra** [comment]
@ezimuel  Tests provided 

---

Originally posted by @AdamiecRadek at https://github.com/zendframework/zend-db/pull/160#issuecomment-286067559

**Comment by michalbundyra** [comment]
This repository has been moved to laminas/laminas-db. If you feel that this patch is still relevant, please re-open against that repository, and reference this issue. To re-open, we suggest the following workflow:
 - Squash all commits in your branch (`git rebase -i origin/{branch}`)
 - Make a note of all changed files (`git diff --name-only origin/{branch}...HEAD
 - Run the laminas/laminas-migration tool on the code.
 - Clone laminas/laminas-db to another directory.
 - Copy the files from the second bullet point to the clone of laminas/laminas-db.
 - In your clone of laminas/laminas-db, commit the files, push to your fork, and open the new PR.
 We will be providing tooling via laminas/laminas-migration soon to help  automate the process.

---

Originally posted by @michalbundyra at https://github.com/zendframework/zend-db/pull/160#issuecomment-575304750

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
