### ISSUE TITLE
Adding the missing method to the interface

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#102]
```
<?php
/**
 * Zend Framework (http://framework.zend.com/)
 *
 * @link      http://github.com/zendframework/zf2 for the canonical source repository
 * @copyright Copyright (c) 2005-2016 Zend Technologies USA Inc. (http://www.zend.com)
 * @license   http://framework.zend.com/license/new-bsd New BSD License
 */

namespace Zend\Db\TableGateway;

interface TableGatewayInterface
{
    public function getTable();
    public function select($where = null);
    public function insert($set);
    public function update($set, $where = null);
    public function delete($where);
    public function getLastInsertValue();
}
```

---

Originally posted by @mariuszjarzab at https://github.com/zendframework/zend-db/issues/155

**Comment by michalbundyra** [comment]
Adding a method to an interface is a backwards compatibility break, as any implementations _must_ update their code in order to be compatible. As such, I'm marking this for v3.0.

One thing we _can_ do now is to add a _new_ interface defining that method, and then have it composed into our own implementations; v3 would then wrap that functionality in the original interface and remove the new one (or extend the new one).

Feel free to submit one or more pull requests per my suggestions above.


---

Originally posted by @weierophinney at https://github.com/zendframework/zend-db/issues/155#issuecomment-240786829

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
