### ISSUE TITLE
Deletion of table entries by ID in an associated table

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#104]
Sometimes the database contains tables like `foo` and `bar` with an `n:m` relationship between them, that is implemented as an association table `foo_bar` (with `FOREIGN KEY`s to `foo.id` and to `bar.id`).

``` sql
CREATE TABLE IF NOT EXISTS `my_db`.`bar` (
  `id` INT UNSIGNED NOT NULL,
  ...
  PRIMARY KEY (`id`)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `my_db`.`foo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `my_db`.`foo_bar` (
  `bar_id` INT UNSIGNED NOT NULL,
  `foo_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`bar_id`, `foo_id`),
  CONSTRAINT `fk_foo_bar_bar`
    FOREIGN KEY (`bar_id`)
    REFERENCES `my_db`.`bar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_foo_bar_foo`
    FOREIGN KEY (`foo_id`)
    REFERENCES `my_db`.`foo` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
```

It would be nice to be able to **delete all `foo` entries by `bar.id`.** In SQL it works like this (s. [here](http://www.mysqltutorial.org/mysql-delete-join/)):

``` sql
DELETE `foo` FROM `foo`
INNER JOIN `foo_bar` ON `foo_bar`.`foo_id` = `foo`.`id`
INNER JOIN `bar` ON `bar`.`id` = `foo_bar`.`bar_id`
WHERE `bar`.`id` = ?
```

In `Zend\Db` it doesn't seem to be implemented. At least I don't see any possibility to set the value for between `DELETE` and `FROM`, s. [here](https://github.com/zendframework/zend-db/blob/master/src/Sql/Delete.php#L33) (also no way to set multiple tables after `FROM`). If I'm wrong, please show, how it works. Otherwise this can be considered as a feature request. ;)

---

Originally posted by @automatix at https://github.com/zendframework/zend-db/issues/147

**Comment by michalbundyra** [comment]
> ``` sql
> DELETE `foo` FROM `foo`
> INNER JOIN
> ```

This is not a part of ANSI SQL standard. So 👎  on this.
A subselect should help.


---

Originally posted by @froschdesign at https://github.com/zendframework/zend-db/issues/147#issuecomment-231332611

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
