### ISSUE TITLE
new Sql($adapter) should propagate with sql statement

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#105]
re-create of https://github.com/zendframework/zendframework/pull/6767

---

Originally posted by @samsonasik at https://github.com/zendframework/zend-db/pull/144

**Comment by michalbundyra** [comment]
@samsonasik unit tests should be leveraging the mocks in this case, can you please take a look and update the unit tests?


---

Originally posted by @mwillbanks at https://github.com/zendframework/zend-db/pull/144#issuecomment-238659590

**Comment by michalbundyra** [comment]
@mwillbanks do you means I need to mock the `Adapter` ? The tests that was added already using real Adapter.


---

Originally posted by @samsonasik at https://github.com/zendframework/zend-db/pull/144#issuecomment-238666879

**Comment by michalbundyra** [comment]
@mwillbanks do you means I need to mock the `Adapter` ? The tests that was added already using real Adapter.


---

Originally posted by @samsonasik at https://github.com/zendframework/zend-db/pull/144#issuecomment-238666883

**Comment by michalbundyra** [comment]
what I need to do if I need execute same sql on different db?
create new sql statement?

---

Originally posted by @turrsis at https://github.com/zendframework/zend-db/pull/144#issuecomment-266797187

**Comment by michalbundyra** [comment]
I guess that should **not** be worked to be re-used query, if there is a case like that, we may do something like this:

```php
$firstAdapter = new Adapter([...]);
$secondAdapter = new Adapter([...]);

function repeatSql(Sql $sql)
{
    // create new update query
    $update = $sql->update('table');
    $update->where(array('id'=>1));
    $update->set(array('foo'=>'bar'));

    return $update;
}

$sql = new Sql($firstAdapter);
echo repeatSql($sql)->getSqlString();

$sql = new Sql($secondAdapter);
echo repeatSql($sql)->getSqlString();
```

---

Originally posted by @samsonasik at https://github.com/zendframework/zend-db/pull/144#issuecomment-266801373

**Comment by michalbundyra** [comment]
That looks so bad. An SQL statement builder that depends on adapter, even though the whole point is not worry about vendor specific, and then have to recreate whole object just because one dependency changed?  Makes user feel as if strategy pattern or similar is used on surface, but misleads you and forces to recreate it. Constructor should maybe take adapter as optional parameter and then have a setter for it. That way, 

```
$sql = new Sql();

$adapter1 = new Adapter();
$adapter2 = new Adapter();

$sql->setAdapter($adapter1);
echo $sql->getSqlString();

$sql->setAdapter($adapter2);
echo $sql->getSqlString();
```

And if forgotten to specify adapter, throw exception.

---

Originally posted by @alextech at https://github.com/zendframework/zend-db/pull/144#issuecomment-266804474

**Comment by michalbundyra** [comment]
there is no `setAdapter()` in Sql class even before it. To do that, we may need to add `Zend\Db\Adapter\AdapterAwareTrait` into Sql class ?

---

Originally posted by @samsonasik at https://github.com/zendframework/zend-db/pull/144#issuecomment-266805252

**Comment by michalbundyra** [comment]
Yes, I meant as an API improvement. But preferably without aware trait, since SM 3 worked on not using those anymore. Or maybe this is an acceptable exception.

---

Originally posted by @alextech at https://github.com/zendframework/zend-db/pull/144#issuecomment-266805883

**Comment by michalbundyra** [comment]
But then @turrsis already has PR which separates this annoyance into SQL as abstract declarative object, and builder which parses it based on adapter (hope thats a decent description). Maybe can sit this out until that gets reviewed and pulled in as a proper solution.

---

Originally posted by @alextech at https://github.com/zendframework/zend-db/pull/144#issuecomment-266808222

**Comment by michalbundyra** [comment]
This repository has been moved to laminas/laminas-db. If you feel that this patch is still relevant, please re-open against that repository, and reference this issue. To re-open, we suggest the following workflow:
 - Squash all commits in your branch (`git rebase -i origin/{branch}`)
 - Make a note of all changed files (`git diff --name-only origin/{branch}...HEAD
 - Run the laminas/laminas-migration tool on the code.
 - Clone laminas/laminas-db to another directory.
 - Copy the files from the second bullet point to the clone of laminas/laminas-db.
 - In your clone of laminas/laminas-db, commit the files, push to your fork, and open the new PR.
 We will be providing tooling via laminas/laminas-migration soon to help  automate the process.

---

Originally posted by @michalbundyra at https://github.com/zendframework/zend-db/pull/144#issuecomment-575304864

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
