### ISSUE TITLE
Zend\DB PDO adapter not providing 'options' parameter to PDO driver

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#106]
In Zend\Db\Adapter line 299 the PDO Driver constructor is called without options.
Is there a way to not unset the 'options" parameter or re-inject the $options array in the PdoDriver constructor ?

---

Originally posted by @sophpie at https://github.com/zendframework/zend-db/issues/143

**Comment by michalbundyra** [comment]
> …re-inject the $options array in the PdoDriver constructor ?

And then? What will you do with the options?


---

Originally posted by @froschdesign at https://github.com/zendframework/zend-db/issues/143#issuecomment-231333472

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
