### ISSUE TITLE
Update Select.php

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#107]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

---

Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/6977
User: @alexandretaz
Created On: 2014-12-08T17:32:57Z
Updated At: 2014-12-10T14:55:05Z
Body
Adding the case on _get() magic methods to retrieve the Order Param, this can be useful to manipulate the order param, checking it before send a Query

---
### Comment

User: @Ocramius
Created On: 2014-12-08T17:33:46Z
Updated At: 2014-12-08T17:33:46Z
Body
Requires a related test case.

---
### Comment

User: @Pittiplatsch
Created On: 2014-12-08T18:54:18Z
Updated At: 2014-12-08T18:54:18Z
Body
I'm not sure if `order` should be exposed that way.
For highly sophisticated functionality depending on `Select`'s internal data these can be retrieved via the method `getRawState()`.

`where` and `having` which ARE exposed via `__get()` play a different role in this context: They are objects on their own which are frequently needed for standard use cases like incrementally adding conditions to an existing select object, whereas `order` is a plain array which cannot be modified in the same way anyway by magically `__get()`-fetching it (at least not atm where it isn't returned by reference).

---
### Comment

User: @alexandretaz
Created On: 2014-12-10T14:55:05Z
Updated At: 2014-12-10T14:55:05Z
Body
@Pittiplatsch 
Exposing order make easy to manipulate the query when dealing with grids just sending a new Array; 
IMHO the total issue shoud be transform Order in a Object that implements ArrayObject and use it on the context of the query

---

---

Originally posted by @GeeH at https://github.com/zendframework/zend-db/issues/141

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
