### ISSUE TITLE
IbmDb2 SQL SelectDecorator does not allow offset without limit

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#108]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

---

Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/7186
User: @robob4him
Created On: 2015-02-05T21:59:30Z
Updated At: 2015-11-06T20:11:48Z
Body
The IbmDb2 SQL SelectDecorator is hard-coded to use 'BETWEEN...' for the LIMIT/OFFSET compensations when it is possible to use an offset separate from a limit as would be represented by '> ?' instead of 'BETWEEN...'

---

---

Originally posted by @GeeH at https://github.com/zendframework/zend-db/issues/140

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
