### ISSUE TITLE
ZF2 not including port in dsn parameter

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#109]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

---

Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/7187
User: @pobrejuanito
Created On: 2015-02-06T00:27:48Z
Updated At: 2015-02-28T21:09:21Z
Body
Hi,

I am using 2.2.6, and I am not sure if this is fixed but here it goes:

In `Zend\Db\Adapter\Driver\Pdo\Connection.php` in method `connect()` the port parameter doesn't get included in the final `$dns` string.

---
### Comment

User: @Martin-P
Created On: 2015-02-06T11:47:44Z
Updated At: 2015-02-06T11:47:44Z
Body
Should be possible in ZF 2.2.6, because it was added in ZF 2.0.3 through PR #2622.

---
### Comment

User: @pobrejuanito
Created On: 2015-02-06T16:07:30Z
Updated At: 2015-02-06T16:18:22Z
Body
there is a case when $dsn is set and $pdodriver is not set. I've added a last "else" case to address this. Now it respects the port in the connect() method:

added $port to list of variable initialization:

```
$dsn = $username = $password = $hostname = $database = $port = null;
```

...

```
if (!isset($dsn) && isset($pdoDriver)) {

            $dsn = array();
            switch ($pdoDriver) {
                case 'sqlite':
                    $dsn[] = $database;
                    break;
                default:
                    if (isset($database)) {
                        $dsn[] = "dbname={$database}";
                    }
                    if (isset($hostname)) {
                        $dsn[] = "host={$hostname}";
                    }
                    if (isset($port)) {
                        $dsn[] = "port={$port}";
                    }
                    break;
            }
            $dsn = $pdoDriver . ':' . implode(';', $dsn);
        } elseif (!isset($dsn)) {
            throw new Exception\InvalidConnectionParametersException(
                'A dsn was not provided or could not be constructed from your parameters',
                $this->connectionParameters
            );
        } else {
            // there is a case when $dsn is set and $pdodriver is not set, if so port doesn't get set
            if ( $port !== null) {
                $dsn .= ';port='.$port;
            }
        }
```

It works for me now. Can anyone confirm?

---
### Comment

User: @Martin-P
Created On: 2015-02-06T16:27:25Z
Updated At: 2015-02-06T16:27:25Z
Body

> there is a case when $dsn is set and $pdodriver is not set.

Can you elaborate on that? As far as I know you always need a PDO driver name. Can you show what the DSN you use looks like?

---
### Comment

User: @Martin-P
Created On: 2015-02-06T16:38:00Z
Updated At: 2015-02-06T16:38:00Z
Body
Tested your suggestion _with_ `$dsn` and _without_ `$pdodriver` and still works fine for me:

``` php
public function testDsnWithoutDriverNameAddsPortToDsn()
{
    $this->connection->setConnectionParameters(array(
        'dsn' => 'host=127.0.0.1;charset=utf8;dbname=foo;port=3306',
    ));
    try {
        $this->connection->connect();
    } catch (\Exception $e) {
    }
    $responseString = $this->connection->getDsn();

    $this->assertContains('host=127.0.0.1', $responseString);
    $this->assertContains('charset=utf8', $responseString);
    $this->assertContains('dbname=foo', $responseString);
    $this->assertContains('port=3306', $responseString);
}
```

---
### Comment

User: @pobrejuanito
Created On: 2015-02-06T17:21:14Z
Updated At: 2015-02-06T17:21:14Z
Body
This is what I have in my autoload/local.php

``````
'db' => array(
        'username' => 'root',
        'password' => '',
        'driver'         => 'Pdo',
        'dsn'            => 'mysql:dbname=staging;host=127.0.0.1',
        'driver_options' => array(
            PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES \'UTF8\''
        ),
        'adapters' => array(
            'db1' => array(
                'username' => 'api',
                'password' => 'pass',
                'port' => '30002',
                'driver'         => 'Pdo',
                'dsn'            => 'mysql:host=myhost.net;dbname=db1',
                'driver_options' => array(
                    PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES \'UTF8\''
                ),
            ),
            'db2' => array(
                'username' => 'api',
                'password' => 'pass',
                'port' => '30002',
                'driver'         => 'Pdo',
                'dsn'            => 'mysql:dbname=db2;host=myhost.net,
                'driver_options' => array(
                    PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES \'UTF8\''
                ),
            ),
        ),
    )

___
### Comment
User: @Martin-P
Created On: 2015-02-06T17:49:00Z
Updated At: 2015-02-06T17:49:00Z
Body
Ah, okay, I see where this is going wrong. You are mixing two ways of setting connection parameters: `dsn` *and* `port`. `Zend\Db\Adapter\Pdo\Connection` expects a `dsn` *or* an array of parameters.

You can fix this by adding the port to your `dsn`:
```php
'dsn' => 'mysql:host=myhost.net;dbname=db1;port=30002',
``````

Not sure this needs fixing at all, perhaps an exception should be thrown when mixing `dsn` and an array of parameters? Ping @Ocramius 

---
### Comment

User: @Martin-P
Created On: 2015-02-28T13:48:41Z
Updated At: 2015-02-28T13:48:41Z
Body
Ping @Ocramius @weierophinney 
Can you clarify if this needs a fix or if you consider it not an issue?

---
### Comment

User: @pobrejuanito
Created On: 2015-02-28T20:49:56Z
Updated At: 2015-02-28T20:49:56Z
Body
Have you tried connecting to a different port? I tried to include the port in the string 

```
'dsn' => 'mysql:host=myhost.net;dbname=db1;port=30002' 
```

but it doesn't work. I was pulling my hair out...I had to modifiy Zend/Db/Adapter/Pdo/Connection.php and add the last else case: 

``` php
if (!isset($dsn) && isset($pdoDriver)) {

            $dsn = array();
            switch ($pdoDriver) {
                case 'sqlite':
                    $dsn[] = $database;
                    break;
                default:
                    if (isset($database)) {
                        $dsn[] = "dbname={$database}";
                    }
                    if (isset($hostname)) {
                        $dsn[] = "host={$hostname}";
                    }
                    if (isset($port)) {
                        $dsn[] = "port={$port}";
                    }
                    break;
            }
            $dsn = $pdoDriver . ':' . implode(';', $dsn);
        } elseif (!isset($dsn)) {
            throw new Exception\InvalidConnectionParametersException(
                'A dsn was not provided or could not be constructed from your parameters',
                $this->connectionParameters
            );
        } else {
            // there is a case when $dsn is set and $pdodriver is not set, if so port doesn't get set
            if ( $port !== null) {
                $dsn .= ';port='.$port;
            }
        }
```

Works great now

In the current code, as it loops through, the $dsn string gets rebuilt and leaves out the port specified in the $dsn string. 

---
### Comment

User: @Martin-P
Created On: 2015-02-28T21:09:21Z
Updated At: 2015-02-28T21:09:21Z
Body

> In the current code, as it loops through, the $dsn string gets rebuilt and leaves out the port specified in the $dsn string. 

The problem is `Zend\Db\Adapter\Pdo\Connection` expects a dsn **or** an array of parameters. You provide both and `Zend\Db\Adapter\Pdo\Connection` does not support that.

Please look at my previous comment, I already gave you the solution :wink: When you apply that to your configuration you will get this:

``` php
<?php
'db' => array(
    'username' => 'root',
    'password' => '',
    'driver'         => 'Pdo',
    'dsn'            => 'mysql:dbname=staging;host=127.0.0.1',
    'driver_options' => array(
        PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES \'UTF8\''
    ),
    'adapters' => array(
        'db1' => array(
            'username' => 'api',
            'password' => 'pass',
            // 'port' => '30002', remove this line
            'driver'         => 'Pdo',
            'dsn'            => 'mysql:host=myhost.net;dbname=db1;port=30002', // add it here
            'driver_options' => array(
                PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES \'UTF8\''
            ),
        ),
        'db2' => array(
            'username' => 'api',
            'password' => 'pass',
            // 'port' => '30002', remove this line
            'driver'         => 'Pdo',
            'dsn'            => 'mysql:dbname=db2;host=myhost.net;port=30002', // add it here
            'driver_options' => array(
                PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES \'UTF8\''
            ),
        ),
    ),
)
```

---

---

Originally posted by @GeeH at https://github.com/zendframework/zend-db/issues/139

**Comment by michalbundyra** [comment]
@Martin-P 
Is this still a problem?


---

Originally posted by @froschdesign at https://github.com/zendframework/zend-db/issues/139#issuecomment-231644986

**Comment by michalbundyra** [comment]
@froschdesign 
Don't know if it is considered an issue and asked @Ocramius and @weierophinney about it in my comment of [28 Feb 2015](https://github.com/zendframework/zendframework/issues/7187#issuecomment-76526726).

Sidenote:

> Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/7187

Perhaps it is easier to [link to the website](https://github.com/zendframework/zendframework/issues/7187) (remove the `api` and `repos` part from the link) instead of linking to a JSON representation of the original post?


---

Originally posted by @Martin-P at https://github.com/zendframework/zend-db/issues/139#issuecomment-231681019

**Comment by michalbundyra** [comment]
@Martin-P 
Please look under the issue description and you will find the link to the original ticket. (Marked with "Closed")


---

Originally posted by @froschdesign at https://github.com/zendframework/zend-db/issues/139#issuecomment-231682046

**Comment by michalbundyra** [comment]
@Martin-P 
This can be a problem:

> The problem is `Zend\Db\Adapter\Pdo\Connection` expects a dsn or an array of parameters. You provide both and `Zend\Db\Adapter\Pdo\Connection` does not support that.


---

Originally posted by @froschdesign at https://github.com/zendframework/zend-db/issues/139#issuecomment-231683160

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
