### ISSUE TITLE
Fixed bug in comparison at AbstractTableGateway->executeInsert

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#110]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

---

Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/7217
User: @edsonhoraciojunior
Created On: 2015-02-13T20:13:11Z
Updated At: 2015-02-19T21:29:24Z
Body
When executeInsert is called, sometimes `$insertState['table']` is string or `Zend\Db\Sql\TableIdentifier`, that also happens with `$this->table`.

I got to a case that `$insertState['table']` is string and `$this->table` is `Zend\Db\Sql\TableIdentifier` and that isn't mapped so a Exception is always thrown.

Example:

> $tableGateway = new \Zend\Db\TableGateway\TableGateway('table1', $dbAdapter);
> $sql                  = new \Zend\Db\Sql\Sql($dbAdapter);
> 
> // Prepare a insert with select
> $select = $sql->select('any_table');
> $select->columns(array('column1', 'column2'));
> $select->where('status' => 'active');
> 
> $insert = $sql->insert('table1');
> $insert->columns(array('column1', 'column2'));
> $insert->values($select); //could be $insert->select($select) too 
> 
> $tableGateway->insertWith($insert); // this will call AbstractTableGateway->executeInsert

---
### Comment

User: @sasezaki
Created On: 2015-02-14T06:36:59Z
Updated At: 2015-02-14T06:36:59Z
Body
@edsonhoraciojunior  Could you add unit-test ?

---
### Comment

User: @weierophinney
Created On: 2015-02-19T21:29:24Z
Updated At: 2015-02-19T21:29:24Z
Body
I'd like to schedule this for 2.4, but I need a test case, @edsonhoraciojunior 

---

---

Originally posted by @GeeH at https://github.com/zendframework/zend-db/issues/138

**Comment by michalbundyra** [comment]
Ping @edsonhoraciojunior


---

Originally posted by @froschdesign at https://github.com/zendframework/zend-db/issues/138#issuecomment-231334357

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
