### ISSUE TITLE
return null if 'where' sql is empty

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#111]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

---

Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/7234
User: @samson-fp
Created On: 2015-02-21T02:34:02Z
Updated At: 2015-02-24T16:05:16Z
Body
When a predicate object with no conditions is passed into 'select', it renders down into '()'.  This results in a query like this which is invalid sql:

select ... where ()

---
### Comment

User: @weierophinney
Created On: 2015-02-24T15:46:19Z
Updated At: 2015-02-24T15:46:19Z
Body
Please provide a unit test for this.

---

---

Originally posted by @GeeH at https://github.com/zendframework/zend-db/issues/137

**Comment by samsonasik** [comment]
This already brough 2 times, from `zendframework/zendframework` to `zendframework/zend-db` to `laminas/laminas-db`. The author didn't give the unit test to reproduce the issue. 

I'm closing it. Please re-create PR if there is a unit test that can reproduce it.
