### ISSUE TITLE
Varchar DDL creation error for SQLite

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#112]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

---

Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/7279
User: @debuger
Created On: 2015-02-28T15:08:25Z
Updated At: 2015-11-06T20:50:20Z
Body
DDL column, created with following code 

```
$column = new Ddl\Column\Varchar('column', 255);
$column->setNullable(true);
$column->setDefault('');
```

creates sql 

```
CREATE TABLE "table" (
....
"column" VARCHAR(255)  '',
....
```

which causes SQL error.
Right SQL should be like for integer

```
CREATE TABLE "table" (
....
"column" VARCHAR(255)  DEFAULT '',
....
```

---

---

Originally posted by @GeeH at https://github.com/zendframework/zend-db/issues/136

**Comment by debuger** [comment]
Looks like the issue is outdated

**Comment by michalbundyra** [comment]
@debuger Thanks for the info. Closing
