### ISSUE TITLE
invoke execute() twice passing ParameterContainer, second execution uses old parameters

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#113]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

---

Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/7280
User: @lomo74
Created On: 2015-02-28T15:30:00Z
Updated At: 2015-11-06T20:52:18Z
Body
<code>
$stmt = $adapter->query("SELECT CAST(:num AS INT) AS num");
//first invocation
$params = new ParameterContainer();
$params->offsetSet('num', 1);
echo $stmt->execute($params)->current()['num'] . PHP_EOL;
//second invocation
$params = new ParameterContainer();
$params->offsetSet('num', 2);
echo $stmt->execute($params)->current()['num'] . PHP_EOL;
</code>

output:
1
1

Looking at zend-db/Zend/Db/Adapter/Statement.php line 216 and subsequent:
<code>
        /*\* START Standard ParameterContainer Merging Block */
        if (!$this->parameterContainer instanceof ParameterContainer) {
            if ($parameters instanceof ParameterContainer) {
                $this->parameterContainer = $parameters;
                $parameters = null;
            } else {
                $this->parameterContainer = new ParameterContainer();
            }
        }

```
    if (is_array($parameters)) {
        $this->parameterContainer->setFromArray($parameters);
    }

    if ($this->parameterContainer->count() > 0) {
        $this->bindParametersFromContainer();
    }
    /** END Standard ParameterContainer Merging Block */
```

</code>

$this->parameterContainer is not overwritten, unless either
(a) it is not a ParameterContainer instance
(b) the $parameters passed to the function is an array

During the second invocation, neither of the above is true, so the new parameters are simply ignored and the old ones are used.

The above should look like this IMHO:
<code>
        /*\* START Standard ParameterContainer Merging Block */
        if ($parameters instanceof ParameterContainer) {
            $this->parameterContainer = $parameters;
            $parameters = null;
        } else if (!$this->parameterContainer instanceof ParameterContainer) {
            $this->parameterContainer = new ParameterContainer();
        }

```
    if (is_array($parameters)) {
        $this->parameterContainer->setFromArray($parameters);
    }

    if ($this->parameterContainer->count() > 0) {
        $this->bindParametersFromContainer();
    }
    /** END Standard ParameterContainer Merging Block */
```

</code>

---

---

Originally posted by @GeeH at https://github.com/zendframework/zend-db/issues/135

**Comment by michalbundyra** [comment]
Ouch, this is still an active bug? I just ran into it today using the latest 2.x version of zend-db coupled with SQL Server, PDO and ODBC - combined they actually care about parameter data types (at least on Linux, not Windows), so ParameterContainer was required.

Quick workaround is this because execute() doesn't properly handle being given a container:
`if ($params instanceof ParameterContainer) {`
`$stmt->setParameterContainer($params);`
`}`
`$result = $stmt->execute($params);`

I'll try to get a PR up for execute() handling around `/** START Standard ParameterContainer Merging Block */`...

---

Originally posted by @mcouillard at https://github.com/zendframework/zend-db/issues/135#issuecomment-539553855

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
