### ISSUE TITLE
PDO, PostgreSQL and bool

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#114]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

---

Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/7284
User: @mbn18
Created On: 2015-03-01T17:06:51Z
Updated At: 2015-03-02T13:53:18Z
Body
PDO cast bool values to string so when such value is passed to PostgreSQL it fail:
Example:

```
$value = false;
$sql = "INSERT INTO table (bool_field) VALUES (?);
$this->getAdapter()->query($sql)->execute([$values]);
```

To go around the problem I issue:

```
$value = ($value) ? true : '0';
```

Is it possible to cast such values in the driver?

[Related info](https://github.com/yiisoft/yii/issues/779)

---
### Comment

User: @Ocramius
Created On: 2015-03-02T13:53:18Z
Updated At: 2015-03-02T13:53:18Z
Body
Eventually related:
- doctrine/dbal#527
- doctrine/dbal#564
- doctrine/dbal#632
- doctrine/dbal#625
- doctrine/dbal#670

---

---

Originally posted by @GeeH at https://github.com/zendframework/zend-db/issues/134

**Comment by michalbundyra** [comment]
Related to #125 


---

Originally posted by @froschdesign at https://github.com/zendframework/zend-db/issues/134#issuecomment-233845812

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
