### ISSUE TITLE
Error : Prepared statement needs to be re-prepared

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#116]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

---

Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/7331
User: @balalinux
Created On: 2015-03-17T05:29:20Z
Updated At: 2015-11-06T21:38:55Z
Body
Hi Team,

Not really sure if this is a bug. Im getting the below error while using Zend\Db\Adapter with Mysqli driver.
"Prepared statement needs to be re-prepared"
This happens only for the queries which uses the mysql views.
Any idea on why this occurs ? Google search suggests to use Pdo_Mysql driver to get rid of this problem.
Is this a known issue with Zend2 + Mysqli ? 
Please let me know.

Thanks.

---
### Comment

User: @visitek
Created On: 2015-03-24T20:17:12Z
Updated At: 2015-03-24T20:17:12Z
Body
We had this problem on old mysql. Update is needed.

---
### Comment

User: @balalinux
Created On: 2015-03-25T06:59:33Z
Updated At: 2015-03-25T06:59:33Z
Body
I see that we use 10.0.15-MariaDB-1~trusty-log. Any idea on from which version this would work fine ?

---
### Comment

User: @balalinux
Created On: 2015-05-12T10:24:04Z
Updated At: 2015-05-12T10:24:04Z
Body
Can you please tell me on which version you found this working ?

---
### Comment

User: @Martin-P
Created On: 2015-05-12T14:49:17Z
Updated At: 2015-05-12T14:49:17Z
Body
Perhaps the notes in the MySQL bug report can help: http://bugs.mysql.com/bug.php?id=42041

---

---

Originally posted by @GeeH at https://github.com/zendframework/zend-db/issues/132

**Comment by michalbundyra** [comment]
I've fixed it temporarily with:

``` php
$_reflection = new \ReflectionObject($model);
            $_property   = $_reflection->getProperty('isInitialized');
            $_property->setAccessible(true);
            $_property->setValue($model, false);
            $_property->setAccessible(false);
            $_property = $_reflection->getProperty('sql');
            $_property->setAccessible(true);
            $_property->setValue($model, null);
            $_property->setAccessible(false);
```

it smells, but only way to flush sql from tablegateway


---

Originally posted by @visitek at https://github.com/zendframework/zend-db/issues/132#issuecomment-229069091

**Comment by Nguimjeu** [comment]
In case this is still bothering someone, I just had the same issues working on a ZF1 project. Changing the Adapter from Mysqli to PDO did the trick for me.

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
