### ISSUE TITLE
Zend\Db\Sql\Predicate\Between: Implementation of optional Type parameters

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#117]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

---

Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/7337
User: @Koopzington
Created On: 2015-03-18T09:42:39Z
Updated At: 2015-11-06T20:57:29Z
Body
Today i've used a SQL statement that checked if a value is between the values of 2 columns.
I've tried using Between like this:

<pre><code>$select->where->between(
    500, 
    'minAmount', 
    'maxAmount'
);</code></pre>

Since the format currently is fixed to "Identifier BETWEEN Value AND Value", I'd like to see an implementation of optional type params like they're being used in [Zend\Db\Sql\Predicate\Predicate](https://github.com/zendframework/zf2/blob/release-2.3.7/library/Zend/Db/Sql/Predicate/Predicate.php).
In the end i'd be able to build the WHERE condition like this:

<pre><code>$select->where->between(
    500, 
    'minAmount', 
    'maxAmount', 
    $select->where::TYPE_VALUE, 
    $select->where::TYPE_IDENTIFIER, 
    $select->where::TYPE_IDENTIFIER
);</code></pre>

---

---

Originally posted by @GeeH at https://github.com/zendframework/zend-db/issues/131

**Comment by michalbundyra** [comment]
I came here to second this proposal.
Having only the first parameter being treated as an identifier prevents me from using the between() method to query all products where a given date lies between their start and end date:

SELECT \* FROM products WHERE '2016-11-02' BETWEEN onlineStart AND onlineEnd;

How is this to be done? Do I really need to use where->greaterThanOrEqualTo() and where->lessThanOrEqualTo()?


---

Originally posted by @Estigy at https://github.com/zendframework/zend-db/issues/131#issuecomment-257854484

**Comment by michalbundyra** [comment]
After 2 hours of making a PR for this i've seen [this](https://github.com/zendframework/zend-db/blob/release-2.8.2/test/Sql/Predicate/BetweenTest.php#L129) in the Test.
So theoretically this worked all the time if you setup the select like this:

``` php
$select->where->between(
    ['2016-11-02' => Between::TYPE_VALUE],
    ['onlineStart' => Between::TYPE_IDENTIFIER],
    ['onlineEnd' => Between::TYPE_IDENTIFIER]
);
```

Now i'm wondering if i should still do the PR or not...


---

Originally posted by @Koopzington at https://github.com/zendframework/zend-db/issues/131#issuecomment-257911420

**Comment by michalbundyra** [comment]
This seems to cover everything we both do need - but we were missing some documentation on this.

So from my perspective it is not so much a feature request but a documentation completion request now.

Great you found it, thanks @Koopzington !


---

Originally posted by @Estigy at https://github.com/zendframework/zend-db/issues/131#issuecomment-257964871

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
