### ISSUE TITLE
We can't create a multiple connection with Pgsql

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#119]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

---

Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/7377
User: @wandersonwhcr
Created On: 2015-03-27T19:54:03Z
Updated At: 2015-04-03T01:47:43Z
Body
Olá pessoas!

I'm trying to use a multiple connection with `pgsql` adapter, but it _always_ retrieve the same PHP resource, even setting a multiple configuration in `ServiceManager`.

Why?

http://php.net/manual/en/function.pg-connect.php

If we use same configuration in both connections, we'll always receive same resource. But if we pass `PGSQL_CONNECT_FORCE_NEW` parameter, all works fine.

[8d603705 master Zend\Db\Adapter\Driver\Pgsql\Connection](https://github.com/zendframework/zf2/blob/8d603705224076429540aa38af7f74e9e3079b85/library/Zend/Db/Adapter/Driver/Pgsql/Connection.php)

Thanks.

---
### Comment

User: @samsonasik
Created On: 2015-04-03T01:47:43Z
Updated At: 2015-04-03T01:47:43Z
Body
linked with #7396

---

---

Originally posted by @GeeH at https://github.com/zendframework/zend-db/issues/129

**Comment by samsonasik** [comment]
I'm closing it as there is PR for it that merged at https://github.com/zendframework/zendframework/pull/7396
