### ISSUE TITLE
Using TableGateway::update() or TableGateway::delete() fails when table has an alias

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#120]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

---

Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/7430
User: @mirfilip
Created On: 2015-04-07T13:57:06Z
Updated At: 2015-11-06T21:16:13Z
Body
This is a continuation of #7311, I should have been more precise with previous bug description for `Insert`.

For technical background please refer to #7311. I've verified the fix and it was correct for `Insert`, however, for `Update` and `Delete` - the behaviour is still buggy.

As @weierophinney investigated in #7311 `Zend\Db\Sql\Sql::prepareStatementForSqlObject()` should get unaliased table name from `Zend\Db\TableGateway\AbstractTableGateway::executeUpdate()/executeDelete()`.

Technically, there are two approaches to the problem. While no flavour of SQL allows aliases for `insert` (at least AFAIK), **some** platforms do allow aliases in `update` and `delete`. It has a different syntax, but it works. 
Example for **SQL Server**:
`DELETE U FROM Users AS U WHERE id = 1`
or 
`UPDATE U SET U.Name = 'Any' FROM Users U WHERE U.ID = 1`

So, first and easy approach is to pass unaliased table (as done in `Insert`). Second is to use alternative syntax but it's not platfiorm agnostic (and I believe ZF2 maintains compatibility in DBAL).

---

---

Originally posted by @GeeH at https://github.com/zendframework/zend-db/issues/128

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
