### ISSUE TITLE
SQL functions miscast boolean values

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#123]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

---

Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/7543
User: @hschletz
Created On: 2015-05-23T09:02:46Z
Updated At: 2015-11-06T21:50:08Z
Body
This does not work (tested with SQLite):

```
$select->where(array('column1' => true, 'column2' => false));
```

which results in

```
... WHERE column1 = '1' AND column2 = ''
```

The first one is ugly, but works as expected while the second does not.

I can work around it by using 0 instead of FALSE, but these surrogates are awful and unintuitive - a number is not really a boolean. A Zend\Db\Sql\Literal would work too, but that's a lot of typing for a simple primitive. The SQL generating code should treat boolean values as such and generate literal TRUE and FALSE.

---

---

Originally posted by @GeeH at https://github.com/zendframework/zend-db/issues/125

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
