### ISSUE TITLE
ZF2 tablegateway Update dangerous!!!

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#124]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

---

Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/7595
User: @netroby
Created On: 2015-06-25T09:16:47Z
Updated At: 2015-12-21T07:47:55Z
Body
ZF2 tablegateway Update dangerous!!!

We occurs problem when using TableGateway.

Think about a normal code:

```
$tableGateWay->update(['age' = 12], $id);
```

Oh, no, holly shit. all the table record been overwriten .

And the Zend Framework Db can not detect and prevent the dangerous usage.

Yeah, you killed me.

---
### Comment

User: @Bittarman
Created On: 2015-06-25T09:36:55Z
Updated At: 2015-06-25T09:36:55Z
Body
But this is the expected behaviour for running an update with a where predicate which would resolve for every row.

Yes its bad when you get it wrong, but thats no different from running an update like _UPDATE foo SET bar=1 WHERE 1;_ The problem really is in the understanding of how this works. 

I'm adding a label for needs documentation, as I don't think this really needs any code changes.

---
### Comment

User: @froschdesign
Created On: 2015-06-25T09:39:15Z
Updated At: 2015-06-25T09:39:15Z
Body

> I'm adding a label for needs documentation, as I don't think this really needs any code changes.

:+1: 

---
### Comment

User: @netroby
Created On: 2015-06-25T09:53:08Z
Updated At: 2015-06-25T09:53:08Z
Body
The type mistake will destory the whole table, I am very sad, I shoot on my feet. hope you guys never face this situation like me.

---
### Comment

User: @netroby
Created On: 2015-06-25T09:57:11Z
Updated At: 2015-06-25T09:57:11Z
Body
No safe guarantee, no lucky

---
### Comment

User: @netroby
Created On: 2015-06-25T10:00:18Z
Updated At: 2015-06-25T10:00:18Z
Body
I suggest , we should check if an update have a where query parameters. If no , throw exception and stop.  Save our life , from got big damage to our database. We will no chance to save our work if we made a small mistake. Very expensive , very hard effort.

---
### Comment

User: @netroby
Created On: 2015-06-25T10:01:18Z
Updated At: 2015-06-25T10:01:18Z
Body
I almost destroyed my company by this accident.

---
### Comment

User: @Bittarman
Created On: 2015-06-25T10:02:10Z
Updated At: 2015-06-25T10:02:10Z
Body
Absolutely not, having no where clause is perfectly valid, we can't make a BC break which makes a perfectly normal valid operation impossible.

---
### Comment

User: @netroby
Created On: 2015-06-25T10:32:13Z
Updated At: 2015-06-25T10:32:24Z
Body
Can we add one more SafeTableGateway ?

code like this :+1: 

``` php
<?php
namespace com\netroby;

use \Zend\Db\TableGateway\TableGateway;

use Zend\Db\Adapter\AdapterInterface;
use Zend\Db\ResultSet\ResultSetInterface;
use Zend\Db\Sql\Sql;

class SafeTableGateway extends TableGateway
{
    /**
     * Constructor
     *
     * @param string|TableIdentifier|array                                              $table
     * @param AdapterInterface                                                          $adapter
     * @param Feature\AbstractFeature|Feature\FeatureSet|Feature\AbstractFeature[]|null $features
     * @param ResultSetInterface|null                                                   $resultSetPrototype
     * @param Sql|null                                                                  $sql
     *
     * @throws Exception\InvalidArgumentException
     */
    public function __construct($table, AdapterInterface $adapter, $features = null, ResultSetInterface $resultSetPrototype = null, Sql $sql = null)
    {
        parent::__construct($table, $adapter, $features = null, $resultSetPrototype = null, $sql = null);
    }
    /**
     * Delete
     *
     * @param  Where|\Closure|string|array $where
     * @return int
     */
    public function delete($where)
    {
        if (is_string($where) || is_numeric($where) || is_bool($where)) {
            throw new \InvalidArgumentException("Not allowd string|int|bool here");
        }
        return parent::delete($where);
    }

    /**
     * Update
     *
     * @param  array $set
     * @param  string|array|\Closure $where
     * @return int
     */
    public function update($set, $where = null)
    {
        if (is_string($where) || is_numeric($where) || is_bool($where)) {
            throw new \InvalidArgumentException("Not allowd string|int|bool here");
        }
        return parent::update($set, $where);
    }
}
```

---
### Comment

User: @netroby
Created On: 2015-06-25T10:32:50Z
Updated At: 2015-06-25T10:32:50Z
Body
This will help who have the same trouble like me, save our life.

---
### Comment

User: @DASPRiD
Created On: 2015-06-25T10:42:04Z
Updated At: 2015-06-25T10:42:04Z
Body
You are free to use such a class in your own codebase. There is no need to bring something like that into the ZF core.

---
### Comment

User: @froschdesign
Created On: 2015-06-25T10:51:21Z
Updated At: 2015-06-25T10:51:21Z
Body

> Can we add one more SafeTableGateway ?

No, because a string is allowed. (Also in your code example -> DocBlock!)

``` php
$table->update(['foo' => 'bar'], 'id = 2');
```

This will be passed as an expression.

> …save our life.

Tests will save your life.

---
### Comment

User: @netroby
Created On: 2015-06-25T11:42:09Z
Updated At: 2015-06-25T11:42:09Z
Body
Thanks your times

---
### Comment

User: @Bittarman
Created On: 2015-06-25T11:43:47Z
Updated At: 2015-06-25T11:43:47Z
Body
This is really a valid documentation issue, I've looked at the relevant docs and it does not seem very well covered at all

---
### Comment

User: @froschdesign
Created On: 2015-06-25T11:46:18Z
Updated At: 2015-06-25T11:46:18Z
Body

> This is really a valid documentation issue

Right!

---
### Comment

User: @savannahparis
Created On: 2015-12-21T01:00:11Z
Updated At: 2015-12-21T01:01:48Z
Body
I have a response for you $table->update(array('foo' => 'bar'), array('id' => 2)); this ok
when before you instance $dbAdapter and $tableGateway. It's work very well.

exacty --> $tableGateway->update(array('foo' => 'bar'), array('id' => 2));

---
### Comment

User: @nuxwin
Created On: 2015-12-21T01:17:34Z
Updated At: 2015-12-21T07:47:55Z
Body
Well, such mistake should happen in development environments only, where the database should be fully recoverable (testing database). This is an API usage mistake, nothing more. If we start to document every possible mistakes that the developers can do, we will lost a lot of time.

To resume, that issue should be put in the box of complaints about  the `poor` ZF documentation. Generally speaking, those complaints come from users that are not happy because they must think instead of copy/past code from the documentation. Having a documentation strickly based on specifications is much better from my point of view because the developers must really learn before doing anything by closing eyes.

---
### Comment

User: @netroby
Created On: 2015-12-21T02:05:28Z
Updated At: 2015-12-21T02:05:28Z
Body
I guess document useless. the problems  will be all the time during coding. Even you have document, but you will forgot it sometimes. Like you drunk or drugs too much. so we have to put a strict ,limit the api behaviour. to prevent bad things happen.

---
### Comment

User: @zf2timo
Created On: 2015-12-21T07:23:57Z
Updated At: 2015-12-21T07:23:57Z
Body
To Change all entries in a DB is an absolutely valid use case and the Framework should not catch things like this.
You can't even define `bad things`. In your project changing the age of all persons to 12 is maybe a bad thing  - but in in other projects its maybe useful to mark all entries in a table as invalid.

So a Framework is a toolbox. And if you want to smash your fingers with a hammer, you can do that. Think about what you are doing, and you will be fine. 

---

---

Originally posted by @GeeH at https://github.com/zendframework/zend-db/issues/123

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
