### ISSUE TITLE
Zend DB TableGateway should support join with table name alias

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#125]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

---

Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/7600
User: @netroby
Created On: 2015-07-01T03:23:15Z
Updated At: 2015-11-06T22:06:05Z
Body
See a small piece code like this:

```
use \Zend\Db\TableGateway\TableGateway
$tableGW = new TableGateway(['a' => 'users'], $dbAdapter);
$tableGW->select(function (Select $s) {
    $s->join(['b' => 'details'], "b.uid = a.uid", ['mobile', 'email'], $s::JOIN_LEFT)
        ->join(['c' => 'orders'], "c.uid = a.uid", ['order_uiqid', 'order_price'], $s::JOIN_LEFT)
        ->order('c.id desc')->limit(10);
}
```

This code using table name alias, that we can easier wrote code and easier to maintain.

---

---

Originally posted by @GeeH at https://github.com/zendframework/zend-db/issues/122

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
