### ISSUE TITLE
AbstractTableObject not define SchemaName 

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#126]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

---

Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/7658
User: @memorrex
Created On: 2016-01-09T21:34:17Z
Updated At: 2016-02-13T15:31:56Z
Body
SchemaName is only defined in ConstraintObject and ColumnObject but it's not defined in TableObject  

---
### Comment

User: @jeremyquinton
Created On: 2016-01-14T08:37:31Z
Updated At: 2016-01-14T08:37:31Z
Body
TableObject inherits from AbstractTableObject.php which has it commented out. https://github.com/zendframework/zend-db/blob/master/src/Metadata/Object/AbstractTableObject.php#L16. There might be a reason for it perhaps the commit history has something about it. 

---

---

Originally posted by @GeeH at https://github.com/zendframework/zend-db/issues/120

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
