### ISSUE TITLE
Implementation of the Iterator interface in the Zend\Db\Adapter\Driver\Pdo\Result class

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#129]
Suppose we have a table named `mytable` with more than two rows in our database.
`$driver` is an instance of the Zend\Db\Adapter\Driver\Pdo\Pdo class.
Let's look at the following code:

``` php
$results = $driver->getConnection()->execute('SELECT * FROM mytable');
foreach ($results as $result) {
    // For some reason our loop ends up at the first level
    break;
}
// Next, in another place we do that (with the same $results object):
foreach ($results as $result) {
    echo $result['mycolumn'];    //Here we start from the second row! (though rewind() was executed)
}
```

The problem is with the Zend\Db\Adapter\Driver\Pdo\Result::rewind() method. Let's look at the actual implementation:

``` php
public function rewind()
{
    if ($this->statementMode == self::STATEMENT_MODE_FORWARD && $this->position > 0) {
        throw new Exception\RuntimeException(
            'This result is a forward only result set, calling rewind() after moving forward is not supported'
        );
    }
    $this->currentData = $this->resource->fetch($this->fetchMode);
    $this->currentComplete = true;
    $this->position = 0;
}
```

As we can see, the Exception is thrown when $this->position is greater than 0, but the Exception should be thrown when $this->position is greater than -1.
In addition to this we should correct the current() and next() methods a little bit too if we want to use them not only in foreach loops.

---

Originally posted by @peterr at https://github.com/zendframework/zend-db/issues/93

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
