### ISSUE TITLE
FEATURE REQUEST: join proxy methods

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#132]
What about adding:

leftJoin(...)
rightJoin(...)
innerJoin(...)
outerJoin...()
leftOuterJoin(...)
rightOuterJoin(...)

methods to Sql\Select?

---

Originally posted by @pine3ree at https://github.com/zendframework/zend-db/issues/80

**Comment by michalbundyra** [comment]
My previous comment was wrong! Here ist an update:

Are the proxy methods really needed? The differences between `join` and `leftJoin` methods 
would not be very big.


---

Originally posted by @froschdesign at https://github.com/zendframework/zend-db/issues/80#issuecomment-233848678

**Comment by michalbundyra** [comment]
@froschdesign 
I think that having those join-related proxy methods would make the code (just a little) more fluent and clear: the name of the method appears first so there is no need for the eye to go reading the class constant parameter that represents the type of join.
kind regards


---

Originally posted by @pine3ree at https://github.com/zendframework/zend-db/issues/80#issuecomment-233897485

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
