### ISSUE TITLE
SQLite error on UNION

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#134]
SQLite does not appreciate parentheses in UNION:

``` sql
(SELECT "4" AS "column1") UNION (SELECT "5" AS "column1")
```

``` php
$select = (new Combine())
    ->union(
        [
            (new Select())->columns(['column1' => 4]),
            (new Select())->columns(['column1' => 5])
        ]
    );

$sql  = (new Sql(new Adapter(new PdoDriver(new Connection(new PDO('sqlite::memory:'))))));
$stmt = $sql->prepareStatementForSqlObject($select);
$result = $stmt->execute();
var_dump(iterator_to_array($result));
```

> Zend\Db\Adapter\Exception\RuntimeException: near "(": syntax error

or explicitly on the PHP PDO instance:

> PDOException: SQLSTATE[HY000]: General error: 1 near "(": syntax error

StackOverflow question reference: http://stackoverflow.com/questions/4653124

---

Originally posted by @robob4him at https://github.com/zendframework/zend-db/issues/75

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
