### ISSUE TITLE
Issues with DDL and PostgreSQL

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#135]
I'm not sure if this is something which has already been covered, but recently I've been attempting to use the `AlterTable` and `CreateTable` classes with PostgreSQL and have been hitting an array of errors. These have been primarily caused by:
- Incorrect quoting of schema elements
- Incorrectly generated SQL

On investigating further, the support for PostgreSQL doesn't seem as robust as that for _DB2_, _MySQL_, _Oracle_ or _SQLServer_. Am I missing something here? Or is it worth both implementing a set of Platform classes for PostgreSQL and spending time debugging and correcting the other issues which I've come across?

Would really appreciate feedback regarding this. 

---

Originally posted by @settermjd at https://github.com/zendframework/zend-db/issues/67

**Comment by michalbundyra** [comment]
I am trying to go through available abstraction utilities (data types, constraint types etc.) to check they work with PostgreSQL and update the newly created decorator as I find them.  Can you please share your usage examples that incorrectly generate SQL so I do not miss anything?


---

Originally posted by @alextech at https://github.com/zendframework/zend-db/issues/67#issuecomment-246146664

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
