### ISSUE TITLE
Select->getSqlString returning invalid SQL for LIMIT and OFFSET

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#136]
`getSqlString` quotes the values for LIMIT and OFFSET, which results in int values quoted to strings, which in turn results in a syntax error for example in MySQL.
https://github.com/zendframework/zend-db/blob/master/src/Sql/Select.php#L739
https://github.com/zendframework/zend-db/blob/master/src/Sql/Select.php#L752
#### Very simple test

`$sql = @(new \Zend\Db\Sql\Select)->from('tableName')->limit(10)->offset(0)->getSqlString(new \Zend\Db\Adapter\Platform\Mysql);`

`$sql === "SELECT`tableName`.* FROM`tableName`LIMIT '10' OFFSET '0'"` This is a Syntax error for MySQL and possibly others as well.

I tested this with the PDO driver
https://github.com/zendframework/zend-db/blob/master/src/Adapter/Platform/Mysql.php#L93 quotes the int values to strings.
#### Noteworhty

When preparing and executing the same `Select` as statement the correct sql `"SELECT`tableName`.* FROM`tableName`LIMIT 10 OFFSET 0"` is generated and send to the MySQL server.
#### Possible untested solution

Since `Select->limit(numeric $value)` and `Select->offset(numeric $value)` only allow numeric values quoting might be omitted, but I cannot say this for sure as quotes might be needed for other platforms or a different use case might require it.
https://github.com/zendframework/zend-db/blob/master/src/Sql/Select.php#L360-L366
https://github.com/zendframework/zend-db/blob/master/src/Sql/Select.php#L378-L384

Another alternative is adding `quoteLimit($value)` and `quoteOffset($value)` to the platform interface and use them in `processLimit` and `processOffset`

---

Originally posted by @hoppithek at https://github.com/zendframework/zend-db/issues/50

**Comment by michalbundyra** [comment]
The workaround for this is to use `Zend\Db\Sql\Sql::buildSqlString()` instead of `Zend\Db\Sql\Select::getSqlString()`.

Example:

```
// $adapter is a Zend\Db\Adapter\AdapterInterface
// $select is a Zend\Db\Sql\Select
$sqlObject = new Zend\Db\Sql\Sql($adapter);
$sqlString = $sqlObject->buildSqlString($select, $adapter);
```


---

Originally posted by @larsnystrom at https://github.com/zendframework/zend-db/issues/50#issuecomment-204277960

**Comment by michalbundyra** [comment]
@larsnystrom 

This alternative cannot be used when you are using the Zend\Db\Sql\Insert with a Zend\Db\Sql\ISelect
This is using mysql adapter

```
$subSelect = new Select();
$select->from("table");
$select->limit(10)
$select->offset(20)

$insert = new Insert();
$insert->table("insertInto");
$insert->select($select);
```

Then the generated sql string will quote the limit and offset values which is incorrect

```
INSERT INTO `insertInto" SELECT * FROM  `table` LIMIT '10' OFFSET '0'
```

The correct value should be 

```
INSERT INTO `insertInto" SELECT * FROM  `table` LIMIT 10 OFFSET 0
```

Thank you 


---

Originally posted by @h3christophe at https://github.com/zendframework/zend-db/issues/50#issuecomment-207594986

**Comment by michalbundyra** [comment]
My solution was to extend the Zend\Db\Sql\Select File  and "fixed" the functions 

```
protected function processLimit(PlatformInterface $platform, DriverInterface $driver = null, ParameterContainer $parameterContainer = null)
    {
        if ($this->limit === null) {
            return;
        }
       if ($parameterContainer) {
            $parameterContainer->offsetSet('limit', $this->limit, ParameterContainer::TYPE_INTEGER);
            return [$driver->formatParameterName('limit')];
        }
        return [intval($this->limit)];
        //return [$platform->quoteValue($this->limit)];
    }

    protected function processOffset(PlatformInterface $platform, DriverInterface $driver = null, ParameterContainer $parameterContainer = null)
    {
        if ($this->offset === null) {
            return;
        }
        if ($parameterContainer) {
            $parameterContainer->offsetSet('offset', $this->offset, ParameterContainer::TYPE_INTEGER);
            return [$driver->formatParameterName('offset')];
        }
        return [intval($this->offset)];
        //return [$platform->quoteValue($this->offset)];
    }
```

I am using 

```
return [intval($this->offset)];
```

instead of 

```
return [$platform->quoteValue($this->offset)];
```

I am not sure if this is the way to go though.... i have not tested all the scenarios 


---

Originally posted by @h3christophe at https://github.com/zendframework/zend-db/issues/50#issuecomment-207596631

**Comment by michalbundyra** [comment]
Hard to believe that this is still open after 4.5 years. Probably because a workaround exits?

---

Originally posted by @bartmcleod at https://github.com/zendframework/zend-db/issues/50#issuecomment-487600110

**Comment by Tommuh** [comment]
I just had the same issue, I searched for a solutions - found this topic. Not really high hopes if this is still broken.

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
