### ISSUE TITLE
Native Firebird driver (without PDO)

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#140]
I would like to see a native Firebird driver like we had in ZF1 that does not rely on PDO.

I have already created a Zend-Db Firebird driver that uses the native ibase_ functions. I can connect to the database, execute queries and return results.

However I need some help/advice on how to deal with Firebird's syntax for FIRST x SKIP y (equivalent to LIMIT x OFFSET y). This goes at the beginning of the SELECT clause, not at the end like MySQL. I think this would impact the Zend\Db\Sql\Select class. Which is a bigger impact that just adding some new driver classes.

I would also appreciate any advice on writing new tests, or using existing zend-db tests.  

---

Originally posted by @srayner at https://github.com/zendframework/zend-db/issues/37

**Comment by michalbundyra** [comment]
This is work in progress but my fork which includes Firebird driver is here; https://github.com/srayner/zend-db

I need help getting started with testing.


---

Originally posted by @srayner at https://github.com/zendframework/zend-db/issues/37#issuecomment-140658399

**Comment by michalbundyra** [comment]
A while that this issue this stop I think we should discuss it, what is the opinion of you?


---

Originally posted by @juizmill at https://github.com/zendframework/zend-db/issues/37#issuecomment-257662803

**Comment by cchable** [comment]
Hello,

It is true that ZF does not support Firebird natively and the PDO version is not perfect.
As the syntax of the "LIMIT x OFFSET y" is not the same with Firebird, it is impossible to use the Paginator... whatever...

In PDO, I created my own class (FBSelect) that extends Select and I can use Paginator transparently :-)

**Comment by MartinKoeditz** [comment]
If it's still interesting. Since Firebird 2.0 you can use SQL compliant ROWS clause. 
[https://firebirdsql.org/refdocs/langrefupd20-select.html#langrefupd20-select-rows](url)

I would also like to see a native driver.

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
