### ISSUE TITLE
$AlterTable->dropConstraint() Throw error on MySQL,There is no support for "DROP CONSTRAINT"

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#141]
I'm dropping a constraint on mysql5.6, code:

``` php
$AlterTable = new Ddl\AlterTable($test_table_name);
$AlterTable->dropConstraint('text_UniqueKey');

echo $sql->buildSqlString($AlterTable,$adapter);

$adapter->query(
    $sql->buildSqlString($AlterTable,$adapter),
    $adapter::QUERY_MODE_EXECUTE
);
```

And this code output :

``` sql
ALTER TABLE `test` DROP CONSTRAINT `text_UniqueKey`
```

Here is the problem, Mysql nerver support the Syntax "DROP CONSTRAINT", so it throw an error :

``` bash
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CONSTRAINT `text_UniqueKey`' at line 2
```

Note: $adapter config array is 

``` php
'db' => array(
    'driver' => 'Pdo_Mysql',
    'hostname' => 'localhost',
    'username' => 'root',
    'password' => 'abc123',
    'database' => 'easypay',
)
```

Help ! What to do now ???

---

Originally posted by @solody at https://github.com/zendframework/zend-db/issues/36

**Comment by michalbundyra** [comment]
Interested in this issue too. I guess there should be a way to do this through the MySQL `AlterTable` decorator.

---

Originally posted by @nanawel at https://github.com/zendframework/zend-db/issues/36#issuecomment-302941517

**Comment by michalbundyra** [comment]
Yes, you can see example in my MSSQL PR at https://github.com/zendframework/zend-db/pull/231/files and more specifically https://github.com/zendframework/zend-db/pull/231/files#diff-1c04a65ef544d7ab52700dcd9818209e

Generally speaking:
1. Extend existing decorator into your project, and use that decorator (or modify sources in your own zend db fork)
2. Modify inherited $specifications property to provide a template for what syntax should be with `printf` style placeholders 
3. add `processWhatever` function, which matches the key of $specifications template you added, or trying to modify. It should return array that will be able to fill placeholders from step 2.

Did not realize some syntax does not work for mysql here. Usually its the other way around. What is appropriate mysql way of doing this?

---

Originally posted by @alextech at https://github.com/zendframework/zend-db/issues/36#issuecomment-302942241

**Comment by michalbundyra** [comment]
> Did not realize some syntax does not work for mysql here. Usually its the other way around. What is appropriate mysql way of doing this?

In MySQL, `DROP CONSTRAINT` is replaced by `DROP FOREIGN KEY` for foreign key constraints only.
*Edit: there's no `DROP CONSTRAINT` at all on this platform, you must use the type of the constraint when dropping.*

My problem here is that I don't want to break the abstraction layer by using explicitly a MySQL-oriented class in my application (it should work the same on MySQL **and** SQLite for example).

So I can't add a new method `dropForeignKey()` because it would break that abstraction, and moreover I use an `AlterTable` object, which does not provide this method before being decorated (which happens later, when the SQL string is generated).

---

Originally posted by @nanawel at https://github.com/zendframework/zend-db/issues/36#issuecomment-302953343

**Comment by michalbundyra** [comment]
This is not a first time I ran into problem of constraints and foreign keys used interchangeably in syntax generation. @ezimuel Should version 3 or maybe even next 2.x consider providing separate API for constraint vs FKs? (not easiest question, because some DB engines do use them interchangeably)

A horrible suggestion for now to keep abstraction layer between your MySQL and SQLite engines same, is on `dropConstraint()` call do a meta data query against DB engine to see if its a constraint or FK XD

---

Originally posted by @alextech at https://github.com/zendframework/zend-db/issues/36#issuecomment-302954164

**Comment by michalbundyra** [comment]
Yeah that's probably what I'll have to do, but that's an ugly workaround.
My idea was also to provide a generic additional (and optional) argument to those methods to allow passing more details at call time. Those parameters would be stored with the rest, and decorators would be able to use them.

In that very case, you could call
```php
$alterTable = new AlterTable();
$alterTable->dropConstraint('MY_FK', ['type' => 'foreign_key']);
```
and then  `\Zend\Db\Sql\Platform\Mysql\Ddl\AlterTableDecorator` would be able to generate the right SQL string via `processDropConstraints()` method.
Others decorators might just ignore them, and behavior would be handled by the parent method.

---

Originally posted by @nanawel at https://github.com/zendframework/zend-db/issues/36#issuecomment-302954633

**Comment by michalbundyra** [comment]
Your idea looks fine for temporary work around.  Would vote against including something like that in library, because optional parameters create unmaintainable logical path branches that future contributors often forget to keep in mind.

---

Originally posted by @alextech at https://github.com/zendframework/zend-db/issues/36#issuecomment-302955865

**Comment by michalbundyra** [comment]
You're right.
Do you think a
```
public function dropConstraint($name, $type = null) {}
```
would be more acceptable? It's still an optional parameter, but now at least it's clearly identified.

Still searching for a clean way to do this, but I can't see anything with the current architecture.

---

Originally posted by @nanawel at https://github.com/zendframework/zend-db/issues/36#issuecomment-302957186

**Comment by michalbundyra** [comment]
Its the same problem. There are many bugs in PostgreSQL adapter as primary example from top of my head because of inconsistency of optional parameter handling few function calls in.  Only time its considered acceptable if it modifies call in some trivial non-branching way.

Another potential solution maybe to use strategy pattern, where syntax is generated based on parameter type. Currently, dropConstraint() only supports string as parameter, which in itself is bad because it is inconsistent with other parts where `Identifier` metadata object is often used. `addConstraint()` can take in `Constraint` identifier, IIRC. So if I have a nice object oriented schema definition, I cannot use that metadata object definition on constraint removal. Not only is that annoying from DDL usage perspective, it would make this problem easier to solve. `Constraint` metadata object could generate its own code. That is, AlterTable decorator would not be the one generating constraint syntax, but ConstraintDecorator would.

So dropConstraint signature can be changed to take in `Constraint` type object instead of string. Constraint can be overriden using decorator, same way everything else can be decorated, which would allow relatively simpler
```
processDroppedConstraint(Constraint $constraint) {
   return $constraint->getSqlString($this->adapter);
}
```

and `dropConstraint` would just add `$constraint` to removal queue.

---

Originally posted by @alextech at https://github.com/zendframework/zend-db/issues/36#issuecomment-302957987

**Comment by michalbundyra** [comment]
More specifically,

$constraint = new Constraint();
$fk = new ForeignKey();
$table->dropConstraint($constraint); // should work
$table->dropConstraint($fk); // also would work.

---

Originally posted by @alextech at https://github.com/zendframework/zend-db/issues/36#issuecomment-302958409

**Comment by michalbundyra** [comment]
That's much better indeed. I've thought of using typed objects as parameters (and specifically Constraints subclasses) but that meant so much code rewrite that I prefered focusing on finding a quicker way without touching to the signature.

Your solution is really attractive, but personally I can't imagine the whole implementation with the associated validation tests that would be necessary...

---

Originally posted by @nanawel at https://github.com/zendframework/zend-db/issues/36#issuecomment-302958556

**Comment by michalbundyra** [comment]
The other problem is that replacing the current `string` parameter by a `Constraint` object would break the backward compatibility. Do you think the new implementation has to support both?

---

Originally posted by @nanawel at https://github.com/zendframework/zend-db/issues/36#issuecomment-303016666

**Comment by michalbundyra** [comment]
Currently the method `addConstraint()` is defined as follows:
```php
/**
     * @param  Constraint\ConstraintInterface $constraint
     * @return self Provides a fluent interface
     */
    public function addConstraint(Constraint\ConstraintInterface $constraint)
    {
        $this->addConstraints[] = $constraint;

        return $this;
    }
```
`$constraint` being a `\Zend\Db\Sql\Ddl\Constraint\ConstraintInterface`.

IMHO and if I understand what you wrote correctly, using this very class for dropping is not the right way to go, but instead use `\Zend\Db\Metadata\Object\ConstraintObject`. Am I right?
That seems logical to me if for example you want to iterate over an existing structure you've just retrieved by analyzing the DB.

---

Originally posted by @nanawel at https://github.com/zendframework/zend-db/issues/36#issuecomment-303068576

**Comment by michalbundyra** [comment]
@alextech I have an implementation based on what you suggested, with unit tests and all. I'll push a PR soon, but I doubt it could be accepted on the main branch, even though it fixes a currently broken implementation.

---

Originally posted by @nanawel at https://github.com/zendframework/zend-db/issues/36#issuecomment-303104802

**Comment by michalbundyra** [comment]
PR #247 proposed. Hope it will be seriously considered.

---

Originally posted by @nanawel at https://github.com/zendframework/zend-db/issues/36#issuecomment-303155757

**Comment by michalbundyra** [comment]
PR looks much nicer without that string property. 
>That seems logical to me if for example you want to iterate over an existing structure you've just retrieved by analyzing the DB.

Yes, This annoyed me on several occasions.

---

Originally posted by @alextech at https://github.com/zendframework/zend-db/issues/36#issuecomment-303160389

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
