### ISSUE TITLE
ORA-01745: Ungültiger Host-/Bindevariablenname caused by :table

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#142]
In /src/Metadata/Source/OracleMetadata.php#L127 :table is a reserved word and therefore the query fails

---

Originally posted by @lkainers at https://github.com/zendframework/zend-db/issues/28

**Comment by michalbundyra** [comment]
The query does also contain additional line breaks (#125, #128) and a semicolon at the end (#129) 


---

Originally posted by @lkainers at https://github.com/zendframework/zend-db/issues/28#issuecomment-124404972

**Comment by michalbundyra** [comment]
Linking sources: https://github.com/zendframework/zend-db/blob/790123893c01ad597b28652b2a382ac86186c6c8/src/Metadata/Source/OracleMetadata.php


---

Originally posted by @Ocramius at https://github.com/zendframework/zend-db/issues/28#issuecomment-124441930

**Comment by michalbundyra** [comment]
@lkainers what oracle version are you testing against? Also, got an example of a generated query?


---

Originally posted by @Ocramius at https://github.com/zendframework/zend-db/issues/28#issuecomment-124442060

**Comment by michalbundyra** [comment]
Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit

There is no generated query https://github.com/zendframework/zend-db/blob/790123893c01ad597b28652b2a382ac86186c6c8/src/Metadata/Source/OracleMetadata.php#L107 is the query


---

Originally posted by @lkainers at https://github.com/zendframework/zend-db/issues/28#issuecomment-124446215

**Comment by michalbundyra** [comment]
$params = array(
    'driver' => 'Oci8',
    'hostname' => 'host',
    'username' => 'user',
    'password' => pass',
    'port' => '',
);

$connection = new Zend\Db\Adapter\Driver\Oci8\Connection($params);
$driver = new Zend\Db\Adapter\Driver\Oci8\Oci8($connection);
$adapter = new Zend\Db\Adapter\Adapter($driver);

$metadata = new Zend\Db\Metadata\Metadata($adapter);
$metadata->getConstraints('tablename');


---

Originally posted by @lkainers at https://github.com/zendframework/zend-db/issues/28#issuecomment-124512548

**Comment by michalbundyra** [comment]
Here's a PR https://github.com/zendframework/zend-db/pull/34 that would fix this issue


---

Originally posted by @vixriihi at https://github.com/zendframework/zend-db/issues/28#issuecomment-138976221

**Comment by samsonasik** [comment]
it seems already fixed by merged PR https://github.com/zendframework/zend-db/pull/34 .

I am closing this.
