### ISSUE TITLE
Sqlite : Enabling Foreign Key Support 

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#144]
From [Sqlite](https://www.sqlite.org/foreignkeys.html#fk_enable) documentation :

> Foreign key constraints are disabled by default (for backwards compatibility), so must be enabled separately for each database connection. (Note, however, that future releases of SQLite might change so that foreign key constraints enabled by default. Careful developers will not make any assumptions about whether or not foreign keys are enabled by default but will instead enable or disable them as necessary.)

Using it, it's a pain to make it **' for each database connection '** !
So is it possible to activate it by default or adding an option for executing ' pragmas ' directive on connection ??

For the moment i've patched localy the file :
 zend-db/src/Adapter/Driver/Pdo/Connection.php
From line 255 :

``` php
if (isset($charset) && $pdoDriver == 'pgsql') {
   $this->resource->exec('SET NAMES ' . $this->resource->quote($charset));
}
//---------------------------------------------------------------------------------------------------------
//   Sqlite : Enabling Foreign Key Support 
else if ($pdoDriver == 'sqlite' ) {
    $this->resource->exec('PRAGMA foreign_keys = on');
}


```

---

Originally posted by @DontShootMe at https://github.com/zendframework/zend-db/issues/12

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
