### ISSUE TITLE
Add inTransaction() to ConnectionInterface

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#145]
Since the Interface already has beginTransaction() and commit(), i'd suggest adding inTransaction() to the Interface. The property is set by the classes themselves in these both methods so I don't see why inTransaction() shouldn't be added to the interface.
[ConnectionInterface.php](https://github.com/zendframework/zend-db/blob/6adc32db27412ba247a3b5b3a5690f935f1a4dfb/src/Adapter/Driver/ConnectionInterface.php)

[AbstractConnection.php](https://github.com/zendframework/zend-db/blob/4a92e53078d816b42b2c49ee730ff4abb061d5ba/src/Adapter/Driver/AbstractConnection.php#L108)
[IbmDb2/Connection.php](https://github.com/zendframework/zend-db/blob/4a92e53078d816b42b2c49ee730ff4abb061d5ba/src/Adapter/Driver/IbmDb2/Connection.php)
[Mysqli/Connection.php](https://github.com/zendframework/zend-db/blob/4a92e53078d816b42b2c49ee730ff4abb061d5ba/src/Adapter/Driver/Mysqli/Connection.php)
[Oci8/Connection.php](https://github.com/zendframework/zend-db/blob/4a92e53078d816b42b2c49ee730ff4abb061d5ba/src/Adapter/Driver/Oci8/Connection.php)
[Pdo/Connection.php](https://github.com/zendframework/zend-db/blob/4a92e53078d816b42b2c49ee730ff4abb061d5ba/src/Adapter/Driver/Pdo/Connection.php)
[Pgsql/Connection.php](https://github.com/zendframework/zend-db/blob/4a92e53078d816b42b2c49ee730ff4abb061d5ba/src/Adapter/Driver/Pgsql/Connection.php)
[Sqlsrv/Connection.php](https://github.com/zendframework/zend-db/blob/4a92e53078d816b42b2c49ee730ff4abb061d5ba/src/Adapter/Driver/Sqlsrv/Connection.php)

---

Originally posted by @Koopzington at https://github.com/zendframework/zend-db/issues/10

**Comment by michalbundyra** [comment]
https://github.com/zendframework/zend-db/pull/20


---

Originally posted by @adamlundrigan at https://github.com/zendframework/zend-db/issues/10#issuecomment-254674321

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)

**Comment by pine3ree** [comment]
@weierophinney @Ocramius 
Can we reopen this? kind regards!

**Comment by Ocramius** [comment]
I'd say that this component is still security-only, and shouldn't be expanded without a championing maintainer that steps up.
