### ISSUE TITLE
Zend\Db\Sql\Replace?

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#147]
Zend\Db\Sql is missing a way to create a REPLACE INTO table_name VALUES(row_data) statement.
Thought, I'd add this here 'cause apparently noone else was missing that feature.

---

Originally posted by @Koopzington at https://github.com/zendframework/zend-db/issues/6

**Comment by michalbundyra** [comment]
We've purposely **not** implemented the feature in the past, as it's not part of any ANSI SQL standards, which means it would require emulation on many platforms. However, it appears that in recent years, most platforms implement it (see http://troels.arvin.dk/db/rdbms/#functions-REPLACE), and do so in essentially the same way. (SQLite even implements it, though that comparison does not include SQLite.)

As such, we can potentially add it as a feature at this time.


---

Originally posted by @weierophinney at https://github.com/zendframework/zend-db/issues/6#issuecomment-111153946

**Comment by michalbundyra** [comment]
@weierophinney the link you have given refers to the REPLACE string function, rather than REPLACE INTO syntax referred to by @Koopzington 

REPLACE INTO allows one to ask if a matching record exists, and then either INSERT or UPDATE a record depending on the answer, in a single statement.

---

Originally posted by @mattfletcher at https://github.com/zendframework/zend-db/issues/6#issuecomment-300416950

**Comment by michalbundyra** [comment]
@mattfletcher 
> the link you have given refers to the REPLACE string function, rather than REPLACE INTO syntax

Right!

> REPLACE INTO allows one to ask if a matching record exists, and then either INSERT or UPDATE a record depending on the answer, in a single statement.

The same applies here: 

> We've purposely not implemented the feature in the past, as it's not part of any ANSI SQL standards, which means it would require emulation on many platforms.

The problem: every DBMS uses an own implementation outside from any standard. For example:

- PostgreSQL: `INSERT INTO ... ON CONFLICT` (aka "UPSERT")
- Mssql: `WHEN NOT MATCHED BY SOURCE`
- MySQL: `INSERT ... ON DUPLICATE KEY UPDATE`
- SQLite: `INSERT OR REPLACE INTO`

So the labels for this issue are correct: "help wanted"

---

Originally posted by @froschdesign at https://github.com/zendframework/zend-db/issues/6#issuecomment-300432251

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
