### ISSUE TITLE
AbstractRowGateway unset sets null

### ISSUE THREAD

**Issue by happydude** [laminas/laminas-db#150]
### Bug Report

When unseting an offset (column), the offset is set to NULL rather than being removed.

|    Q        |   A
|------------ | ------
| Version(s)  | Since 2.0

#### Summary

When using RowGateway there is no way to unset an offset (column) once it has data. The offsetUnset function sets the value to NULL. https://github.com/laminas/laminas-db/blob/f0184005845f9e7a54d89673cfa38ae95954248c/src/RowGateway/AbstractRowGateway.php#L266-L270

We have a table with a modified timestamp column that has a NOT NULL constraint and a default of "CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP".

We use the row gateway feature and by default it pulls the modifed_ts column, we have to clear that before saving our changes otherwise the same timestamp will be sent back to mysql.

AbstractRowGateway has an __unset magic method that calls offsetUnset that sets the offset to NULL.

This code worked ok with mysql 5.7, because null would be ignored, but mysql 8.0 will error with cannot be null.

```php
$rs = $tableWithRowGatewayFeature->select(array('id' => $id));
$row = $rs->current();
$row->text = 'changed something';
unset($row->modified_ts);
$row->save();
```

#### Current behavior
Calling unset on for a column name that doesn't exist will cause a db error.

#### How to reproduce
```php
$rs = $tableWithRowGatewayFeature->select(array('id' => $id));
$row = $rs->current();
$row->text = 'changed something';
unset($row->DoesNotExist);
$row->save();
```
```sql
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'DoesNotExist' in 'field list'
```

#### Expected behavior
Calling unset or unset functions should unset values rather than setting NULL, if something needs to be NULL the programmer can do that using __set.

Maybe something like:
```php
    public function offsetUnset($offset)
    {
        if(isset($this->data[$offset])) { 
            unset($this->data[$offset]);
        }
        return $this;
    }
```

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
