### ISSUE TITLE
Inconsistency in getRawState results (\Laminas\Db\Sql\* classes)

### ISSUE THREAD

**Issue by scottw-finao** [laminas/laminas-db#151]
I'm not sure if this is supposed to behave this way or not, but noticed it while creating tests for a new factory interface to replace our old Zend_Db with newer \Laminas\Db tools.

If I create a proper adapter, then create a set of the \Laminas\Db\Sql\* objects (what my factory code basically does) using that adapter, I get inconsistent results back from 'getRawState' for the 'table' array key when no table was specified instantiating the object.

Select, and Insert have a value of 'null' for the table key
Update and delete have a value of '' (empty string) for the table key

I know it's not a big thing, and there may be some reasoning behind it, but in case it was a woopsy somewhere I thought it would point it out.

I discovered it as I was creating test cases for the factory wrapper and wanted to basically check that the table was being filled in properly when a table name was provided when calling the factory method for any given Sql\* object type. As a contrast, I was also checking when no table was specified and noticed the differences in the results between the four class types. (I just changed the latter two tests from assertNull() to assertEmpty() for now)

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
