### ISSUE TITLE
Wrong primary key value assignment

### ISSUE THREAD

**Issue by EntityTechnologies** [laminas/laminas-db#159]
### Bug Report

**namespace:** `Laminas\Db\RowGateway`
**class method:** `save()`

There is a possible bug in following lines:

```php
if (($primaryKeyValue = $result->getGeneratedValue()) && count($this->primaryKeyColumn) == 1) {
      $this->primaryKeyData = [$this->primaryKeyColumn[0] => $primaryKeyValue];
 }
```

**Explanation:**

`$primaryKeyValue = $result->getGeneratedValue()` assignment is wrong since the primary key value holder could be a totally different column.  

PDO, for example, returns the first generated auto increment value, while the primary column value could come from data itself (it could happen that primary key value was set before). The current solution is not safe.

#### Summary

**My suggestion:** First of all is to fetch the primary key from data based on primary column definition (`$this->primaryKeyColumn[0]`) and if nothing was found only then fetch from generated value. 

```php
$lastInsertedValue = $result->getGeneratedValue();
if ($lastInsertedValue && count($this->primaryKeyColumn) == 1) {
     $primaryKeyValue = (!empty($this->data[$this->primaryKeyColumn[0]])) ? $this->data[$this->primaryKeyColumn[0]] : null;
    if (!$primaryKeyValue) $primaryKeyValue = $lastInsertedValue;
    $this->primaryKeyData = [$this->primaryKeyColumn[0] => $primaryKeyValue];
}
```

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
