### ISSUE TITLE
Unable to create Identity Column with Postgres

### ISSUE THREAD

**Issue by Fleuv** [laminas/laminas-db#165]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

There is no way to add an [Identity Column](https://www.2ndquadrant.com/en/blog/postgresql-10-identity-columns/) using the classes offered to created DDL's.

This is the closest I've got to achieving this:

```
$column = new Integer('id');
$column->addConstraint(new PrimaryKey());
```

What generates the following SQL:
```
"id" INTEGER NOT NULL PRIMARY KEY
```

I expected to be able to use the `$column->setOption($key, $value)` method to be able to do something like:
```
...
$column->setOption('GENERATED ALWAYS AS IDENTITY', true);
```

And get the following SQL:
```
"id" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY
```

However it unfortunately had no affect.

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
