### ISSUE TITLE
PDO beginTransaction - catch Exception

### ISSUE THREAD

**Issue by tsmgeek** [laminas/laminas-db#167]
|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

A problem ive had since ZF1 is that if an exception is thown in `beginTransaction()` I would not get a `Zend_Db_Adapter_Exception` but rather a `PDOException`.
Seems to me that all methods that call parent PDO methods should catch and rethrow exceptions as `Zend_Db_Adapter_Exceptions`.

Common issues here are due to `SQLSTATE[HY000]: General error: 2006 MySQL server has gone away` messages that become unhandled or I catch them in a general `Exception` state.

Note that my references should be swapped to Laminas.

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
