### ISSUE TITLE
Why is not possible disabling quote identifiers for Mysql platform?

### ISSUE THREAD

**Issue by eguvenc** [laminas/laminas-db#175]
### Feature Request

Why is not possible disabling quote identifiers for Mysql platform?

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

https://discourse.laminas.dev/t/why-is-not-possible-disabling-quote-identifiers-for-mysql-platform/1930/2

**Comment by weierophinney** [comment]
Answered in forum.
