### ISSUE TITLE
Laminas Db Expression - Mysql GROUP_CONCAT - Resultset returns only single/first result of aggregate

### ISSUE THREAD

**Issue by juuce** [laminas/laminas-db#187]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.12.0

#### Summary

Mysql GROUP_CONCAT - Resultset returns only single/first result of aggregate
Using Driver 'PdoMysql' default factory in MVC

#### Current behavior

Using GROUP_CONCAT(id) returns first ID id found and not CSV list of ids
Can confirm phpmyAdmin returns correct CSV list of IDs.

#### How to reproduce

SELECT `cl`.*, `ca`.`label_txt` AS `category`, `ca`.`display_column` AS `display_column`, `sc`.`label_txt` AS `subcategory` FROM (SELECT `chart_linkage`.`cat_id` AS `cat_id`, `chart_linkage`.`subcat_id` AS `subcat_id`, GROUP_CONCAT(`currency_id` SEPARATOR ',') AS `currency_list`, GROUP_CONCAT(`id` SEPARATOR ':') AS `link_ids`, MAX(access_level) AS `access_level` FROM `chart_linkage` GROUP BY `cat_id`, `subcat_id`) AS `cl` LEFT JOIN `chart_category` AS `ca` ON `cl`.`cat_id`=`ca`.`id` LEFT JOIN `chart_category_sub` AS `sc` ON `cl`.`subcat_id`=`sc`.`id` ORDER BY `ca`.`order_nr` ASC, `sc`.`order_nr` ASC

Same result using 
`$dbAdapter->query($sql, $dbAdapter::QUERY_MODE_EXECUTE);`
and
`$sql = $select->getSqlString($this->dbAdapter->getPlatform());
 $statement = $this->dbAdapter->query($sql);
$resultset = $statement->execute();
`
Produces same result
 ["cat_id"]=> string(1) "1" ["subcat_id"]=> string(1) "1" **["currency_list"]=> string(1) "0"** **["link_ids"]=> string(1) "1"** ["access_level"]=> string(7) "premium" ["category"]=> string(29) "Key FX Fundamentals (Summary)" ["display_column"]=> string(1) "1" ["subcategory"]=> string(10) "Key Charts" }

#### Expected behavior

resultset field to have CSV string.

Mysql Resultset

cat_id | subcat_id | currency_list | link_ids | access_level | category | display_column | subcategory |  -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 1 | 0,15,14,13,12,11,9,28,29,8,30,7,6,5,4,3,2,1,17,18,... | 1:111:110:109:108:107:105:104:103:102:101:100:99:9... | premium | Key FX Fundamentals ) | 1 | Key Charts

**Comment by juuce** [comment]
Considered stable and actual results can vary... I'll try the pull request option with tests.

**Comment by froschdesign** [comment]
@juuce 
> I'll try the pull request option with tests.

Before you start your work, please note that this component is in **security-only** maintenance mode. This means that no new pull requests are accepted.
If you found a security problem, please follow our [security reporting guidelines](https://getlaminas.org/security/)

The second option is to [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D) as a maintainer for this component.

Thank you for your understanding.

**Comment by juuce** [comment]
Apologise for this. It was a very long day and I thought I had exhausted all avenues, hence I came here.
Upon review the source/library/module laminas-db is fine, I have/am the bug :). 
It was a data problem.
Again apologise for wasting anyones time.

**Comment by froschdesign** [comment]
@juuce 
No problem at all and thanks for the feedback! 👍
