### ISSUE TITLE
curl get "mssql-server.list" is rotten

### ISSUE THREAD

**Issue by ZVanoZ** [laminas/laminas-db#195]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.13.x 

#### Summary

I cloned repo and do "vagrant up", but have an error during install "mssql-server" 
[VagrantUp-manuality.log](https://github.com/laminas/laminas-db/files/6671346/VagrantUp-manuality.log)

I enter into terminal VirtualBox and check config "mssql-server.list"
$ cat /etc/apt/sources.list.d/mssql-server.list
Result is
> <html>
> <head><title>404 Not Found</title></head>
> <body>
> <center><h1>404 Not Found</h1></center>
> <hr><center>nginx/1.18.0 (Ubuntu)</center>
> </body>
> </html>

Reason - link "https://packages.microsoft.com/config/ubuntu/16.04/mssql-server.list" is wrong in line 31 of "Vagrantfile"
`curl -s https://packages.microsoft.com/config/ubuntu/16.04/mssql-server.list > /etc/apt/sources.list.d/mssql-server.list`

#### Current behavior

Installation of "mssql-server" fail.

#### How to reproduce

$ git clone https://github.com/laminas/laminas-db.git laminas-db.src
$ cd laminas-db.src
$ vagrant up

#### Expected behavior

Installation of "mssql-server" success.

**Comment by clarkphp** [comment]
Thanks for reporting this problem. I may have found the correct URL and will test this week.

**Comment by willjones9** [comment]
@clarkphp Issue #194 has the correct URL for this, however the installation script needs to be updated to correctly choose the edition, which IMHO should be the Developer edition. If memory serves, Developer edition has the same features as Enterprise (or whatever the top tier edition is called), just without production use rights.

**Comment by ZVanoZ** [comment]
This bug was fixed in v.2.14.x
Thank you all.
