### ISSUE TITLE
v.2.14.x has broken link "contributor's guide" in "README.md"

### ISSUE THREAD

**Issue by ZVanoZ** [laminas/laminas-db#208]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.14.x

#### Summary

Click on link "contributor's guide" goes to 404 page.

#### Current behavior

Click on link "contributor's guide" goes to 404 page.

#### How to reproduce

1. Open gihub page for v.2.14.x
https://github.com/laminas/laminas-db/tree/2.14.x
2. Scroll to text "Please be sure to read the contributor's guide for general information on contributing."
3. Click on link "contributor's guide"
Now we have error 404 "This is not the web page you are looking for".

#### Expected behavior

Expected open guide after step 3.

**Comment by Ocramius** [comment]
Could you send a patch to change it to https://github.com/laminas/.github/blob/main/CONTRIBUTING.md please?
