### ISSUE TITLE
Zend\Db\Adapter\AdapterServiceFactory always invoke Zend\Db\Adapter\Adapter

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-db#21]
I created my own `Db\Adapter\AdapterServiceFactory` so I could be able to call my own `Db\Adapter`.

```php
namespace RVMvp\Db\Adapter;

use Interop\Container\ContainerInterface;
use Zend\ServiceManager\ServiceLocatorInterface;
use Zend\Db\Adapter\AdapterServiceFactory as ZendAdapterServiceFactory;

class AdapterServiceFactory extends ZendAdapterServiceFactory
{
    public function createService(ServiceLocatorInterface $container)
    {
        return $this($container, Adapter::class);
    }
}
```

It should create a service of `RVMvp\Db\Adapter\Adapter` but keep creating `Zend\Db\Adapter\Adapter`.

This is happening because the invokable method is calling directly the `Zend\Db\Adapter\Adapter` instead of the requested name provided on `createService` method:

```php
namespace Zend\Db\Adapter;

use Interop\Container\ContainerInterface;
use Zend\ServiceManager\FactoryInterface;
use Zend\ServiceManager\ServiceLocatorInterface;

class AdapterServiceFactory implements FactoryInterface
{
    /**
     * Create db adapter service
     *
     * @param ContainerInterface $container
     * @param string $requestedName
     * @param array $options
     * @return Adapter
     */
    public function __invoke(ContainerInterface $container, $requestedName, array $options = null)
    {
        $config = $container->get('config');
        return new Adapter($config['db']); // HERE IT'S CALLING DIRECTLY
    }

    /**
     * Create db adapter service (v2)
     *
     * @param ServiceLocatorInterface $container
     * @return Adapter
     */
    public function createService(ServiceLocatorInterface $container)
    {
        return $this($container, Adapter::class);
    }
}
```

I did my workaround adding the invokable method to my own `AdapterServiceFactory`:

```php
public function __invoke(ContainerInterface $container, $requestedName, array $options = null)
 {
        $config = $container->get('config');
        return new $requestedName($config['db']); // CHANGED TO REQUESTED NAME
 }
```

I'm suggesting a bugfix so we don't need to override the invokable method.

---

Originally posted by @raivirtual at https://github.com/zendframework/zend-db/issues/353

**Comment by weierophinney** [comment]
>I did my workaround adding the invokable method to my own AdapterServiceFactory:

That is how [Service Manager](https://zendframework.github.io/zend-servicemanager/configuring-the-service-manager/ ) expects factories to be.  Depending on how you configured your service manager, this is not be a problem. I am guessing you have 
```
invokables => [ RVMvp\Db\Adapter\AdapterServiceFactory::class]
```

somewhere in your module confugration?

---

Originally posted by @alextech at https://github.com/zendframework/zend-db/issues/353#issuecomment-458009722

**Comment by weierophinney** [comment]
But it's not calling by Service Manager. It's instancing directly.

---

Originally posted by @raivirtual at https://github.com/zendframework/zend-db/issues/353#issuecomment-458967498

**Comment by weierophinney** [comment]
Hello @raivirtual , You should define a factory for the adapter interface:
```php
'dependencies' => [
    //...
    'factories' => [
        //...
        \Zend\Db\Adapter\AdapterInterface::class => \My\Db\AdapterFactory::class,
        //...
    ],
    //...
],
```

In servicemanager config the `Zend\Db\Adapter\Adapter::class` service name is actually an alias for `Zend\Db\Adapter\AdapterInterface::class::class` (see ConfigProvider in zend-db), but you should build your dependencies upon the `AdapterInterface::class` interface as service name.
kind regards

---

Originally posted by @pine3ree at https://github.com/zendframework/zend-db/issues/353#issuecomment-469100564

**Comment by samsonasik** [comment]
I am closing this. As @pine3ree said, you can map to alias for your own custom factory.
