### ISSUE TITLE
Adding the JOIN_FULL_OUTER class constant, since there are DBMS' out …

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-db#22]
…there which can't handle an unqualified OUTER JOIN. An example of that can be found in PostgreSQL (See: https://www.postgresql.org/docs/11/sql-select.html).

Provide a narrative description of what you are trying to accomplish:

- [ ] Are you fixing a bug?
  - [ ] Detail how the bug is invoked currently.
  - [ ] Detail the original, incorrect behavior.
  - [ ] Detail the new, expected behavior.
  - [ ] Base your feature on the `master` branch, and submit against that branch.
  - [ ] Add a regression test that demonstrates the bug, and proves the fix.
  - [ ] Add a `CHANGELOG.md` entry for the fix.

- [x] Are you creating a new feature?
  - [x] Why is the new feature needed? What purpose does it serve?
  - [x] How will users use the new feature?
  - [ ] Base your feature on the `develop` branch, and submit against that branch.
  - [x] Add only one feature per pull request; split multiple features over multiple pull requests
  - [ ] Add tests for the new feature.
  - [x] Add documentation for the new feature.
  - [ ] Add a `CHANGELOG.md` entry for the new feature.

- [ ] Is this related to quality assurance?
  

- [x] Is this related to documentation?
  
  

---

Originally posted by @galvao at https://github.com/zendframework/zend-db/pull/351

**Comment by samsonasik** [comment]
I've created PR https://github.com/laminas/laminas-db/pull/172 for it
