### ISSUE TITLE
Add Expression as allowed value to Predicate

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-db#23]
Static analysis fails if an Expression object is passed to some methods, thus the updated docblock.

---

Originally posted by @andreasschroth at https://github.com/zendframework/zend-db/pull/348

**Comment by samsonasik** [comment]
I've created PR https://github.com/laminas/laminas-db/pull/171 for it.

**Comment by andreasschroth** [comment]
Looks like ```Laminas\Db\Sql\Expression``` is the correct type instead of ```Laminas\Db\Sql\Predicate\Expression``` ?
