### ISSUE TITLE
ResultSet setArrayObjectProperty incorrect check

### ISSUE THREAD

**Issue by wiryonolau** [laminas/laminas-db#234]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.13.4

#### Summary

The exception said ```'Object must be of type ArrayObject, or at least implement exchangeArray'```

But it check using ```! method_exists($arrayObjectPrototype, 'exchangeArray')```

```php
public function setArrayObjectPrototype($arrayObjectPrototype)
{
  if (
    ! is_object($arrayObjectPrototype) 
    || (
          ! $arrayObjectPrototype instanceof ArrayObject
          && ! method_exists($arrayObjectPrototype, 'exchangeArray')
       )
    ) {
      throw new Exception\InvalidArgumentException(
        'Object must be of type ArrayObject, or at least implement exchangeArray'
      );
  }
  $this->arrayObjectPrototype = $arrayObjectPrototype;
  return $this;
}
```

#### Current behavior

ResultSet throw InvalidArgumentException when passing an object that is not instance of ```ArrayObject``` but has```exchangeArray``` function

```
 ! is_object($arrayObjectPrototype) => false
 ! $arrayObjectPrototype instanceof ArrayObject => true
 ! method_exists($arrayObjectPrototype, 'exchangeArray') => false

result => ( false or false )
```

#### How to reproduce

Try passing an object that has exchangeArray function

#### Expected behavior

Should not throw an Exception

**Comment by Ocramius** [comment]
Was this closed on purpose?

**Comment by wiryonolau** [comment]
Yes sorry, my code somehow pass a string instead of an object. The logic is ok
