### ISSUE TITLE
JOIN incorrect or missing type

### ISSUE THREAD

**Issue by Tommuh** [laminas/laminas-db#291]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.18

#### Summary

When running PHPStan it returns the following type error. I think the typing is wrong of the join block.
When I supply "\Laminas\Db\Sql\Where" as "on" everything works perfectly. But PHPStan throws following error message.

![image](https://github.com/laminas/laminas-db/assets/2089879/82865c58-7867-42ac-bfeb-55f02f532e27)

When I change it to "\Laminas\Db\Sql\Predicate\Expression" I cannot get it to work, not sure if I'm doing something wrong ...

#### How to reproduce

The following code works for me, but PHPStan doesn't like:

```
        $select = new \Laminas\Db\Sql\Select();
        
        $select->from(['a' => new \Laminas\Db\Sql\TableIdentifier('TABLE_CONSTRAINTS', 'INFORMATION_SCHEMA')])
            ->join(
                ['b' => new \Laminas\Db\Sql\TableIdentifier('KEY_COLUMN_USAGE', 'INFORMATION_SCHEMA')],
                (new \Laminas\Db\Sql\Where())
                    ->equalTo('b.CONSTRAINT_NAME', 'a.CONSTRAINT_NAME', 'identifier', 'identifier')
                    ->equalTo('b.CONSTRAINT_SCHEMA', 'a.CONSTRAINT_SCHEMA', 'identifier', 'identifier')                    
                    ->equalTo('b.TABLE_NAME', 'a.TABLE_NAME', 'identifier', 'identifier'), 
                [],
                'inner'
            )                
            ->columns([
                new \Laminas\Db\Sql\Predicate\Expression('b.COLUMN_NAME')
            ])
            ->where((new \Laminas\Db\Sql\Where())
                ->equalTo('a.TABLE_NAME', 'some-dummy-table')                    
                ->equalTo('a.CONSTRAINT_TYPE', 'PRIMARY KEY')                
            ); 
```

This generates the follow correct SQL string:

```
SELECT b.column_name AS Expression1
  FROM   `information_schema`.`table_constraints` AS `a`
 INNER JOIN `information_schema`.`key_column_usage` AS `b`
      ON `b`.`constraint_name` = `a`.`constraint_name`
    AND `b`.`constraint_schema` = `a`.`constraint_schema`
    AND `b`.`table_name` = `a`.`table_name`
WHERE  `a`.`table_name` = 'some-dummy-table'
    AND `a`.`constraint_type` = 'PRIMARY KEY' 
```

Changing it to Predicate\Expression:

```
        $select = new \Laminas\Db\Sql\Select();
        
        $select->from(['a' => new \Laminas\Db\Sql\TableIdentifier('TABLE_CONSTRAINTS', 'INFORMATION_SCHEMA')])
            ->join(
                ['b' => new \Laminas\Db\Sql\TableIdentifier('KEY_COLUMN_USAGE', 'INFORMATION_SCHEMA')],
                new \Laminas\Db\Sql\Predicate\Expression('b.CONSTRAINT_NAME', 'a.CONSTRAINT_NAME'),   ??????????
                [],
                'inner'
            )                
            ->columns([
                new \Laminas\Db\Sql\Predicate\Expression('b.COLUMN_NAME')
            ])
            ->where((new \Laminas\Db\Sql\Where())
                ->equalTo('a.TABLE_NAME', 'some-dummy-table')                    
                ->equalTo('a.CONSTRAINT_TYPE', 'PRIMARY KEY')                
            );

```

After running this I get the following error:
"The number of replacements in the expression does not match the number of parameters".

The Laminas documentation also shows incomplete information because it is missing types:

![image](https://github.com/laminas/laminas-db/assets/2089879/8f949cf5-283d-42bb-9d16-75be591364c6)

**Comment by likeajohny** [comment]
@Tommuh The error "The number of replacements in the expression does not match the number of parameters" is thrown cuz you're using the Expression object wrong.
An Expression expects placeholders in the first argument if a second argument is supplied.
For example:

`new Expression('WHERE name = ?', 'Tommuh')`

In your case you don't need the second argument but want to do it with the first only:
`new \Laminas\Db\Sql\Predicate\Expression('b.CONSTRAINT_NAME ON a.CONSTRAINT_NAME')`.

In the end an expression is just that, an expression.

Also PHPStan is correct with its complaint cuz the annotation for the joins $on parameter states the following:
`@param string|Predicate\Expression $on`.

I can't quite tell how exactly the WHERE is being evaluated inside of the Join but you could also just use a string (`b.CONSTRAINT_NAME ON a.CONSTRAINT_NAME`) as your $on argument and handle the where clauses at the bottom together with the other ones.

**Comment by likeajohny** [comment]
@Tommuh Were you able to work out the issues? Would be great if this ticket could be closed off then.

**Comment by Tommuh** [comment]
@LikeAJohny  - I am very sorry for not replying back. Yes, I managed to resolve this.

A bit late, but thank you for your help.

**Comment by likeajohny** [comment]
Don't worry, just had the same with another issue.
Glad you worked it out 👍
