### ISSUE TITLE
Select::having() can get an Having as parameter

### ISSUE THREAD

**Issue by panvid** [laminas/laminas-db#296]
This is only a phpDoc problem:

https://github.com/laminas/laminas-db/blob/2.19.x/src/Sql/Select.php#L305C1-L305C1

`Select::having($predicate)` could also get an `Having` as `$predicate` parameter. This PhpDoc does not say this.

**Comment by rvm-peercode** [comment]
PR: https://github.com/laminas/laminas-db/pull/295
