### ISSUE TITLE
Fixes #316 : set return null for HydratingResultSet::current() on no data

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-db#30]
Provide a narrative description of what you are trying to accomplish:

- [x] Are you fixing a bug?
  - [x] Detail how the bug is invoked currently.
         call `HydratingResultSet::current()` on no data in current record.
  - [x] Detail the original, incorrect behavior.
         it returns false.
  - [x] Detail the new, expected behavior.
         it returns null, the "AbstractResultset" and "ResultSet" class returns null on no data, so it returns null for consistency/fix.
  - [x] Base your feature on the `master` branch, and submit against that branch.
  - [x] Add a regression test that demonstrates the bug, and proves the fix.
  - [x] Add a `CHANGELOG.md` entry for the fix.

If this is considered a BC break, I can target to develop. Fixes #316

---

Originally posted by @samsonasik at https://github.com/zendframework/zend-db/pull/325

**Comment by weierophinney** [comment]
@samsonasik yes, this is a BC break. Please send it to develop. Thanks!

---

Originally posted by @ezimuel at https://github.com/zendframework/zend-db/pull/325#issuecomment-411045533

**Comment by weierophinney** [comment]
@ezimuel I've rebased against develop branch and change target to develop branch.

---

Originally posted by @samsonasik at https://github.com/zendframework/zend-db/pull/325#issuecomment-411048221

**Comment by ezimuel** [comment]
@weierophinney thanks for managing the issue.

**Comment by froschdesign** [comment]
@ezimuel 
You mean @samsonasik and @michalbundyra. See: https://github.com/laminas/laminas-db/pull/39
(@weierophinney has transfer this issue report from Zend Framework to Laminas.)

**Comment by ezimuel** [comment]
@froschdesign I mean everyone :-) @weierophinney rebased and changed target.
