### ISSUE TITLE
DB Migration

### ISSUE THREAD

**Issue by modir** [laminas/laminas-db#303]
### Feature Request

An official DB migration library which is part of Laminas\Db.

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

The only thing missing for me in Laminas\Db is some official DB migration tool/library which is shipped officially with Laminas\Db e.g as Laminas\Db\Migrator. As the basis I was thinking about something similar to https://github.com/vgarvardt/ZfSimpleMigrations.

**Comment by Ocramius** [comment]
There are already great DB migration libraries out there. For me, most notably:

 * https://www.doctrine-project.org/projects/migrations.html
 * https://sqitch.org/

No need to design more: it's a very crowded space that does not benefit from framework-specific tools.
