### ISSUE TITLE
Wrong links and bad contrast in docs

### ISSUE THREAD

**Issue by trasher** [laminas/laminas-db#31]
This is not directly related to the db component, but I did not find where to report docs issues.

Links on https://docs.laminas.dev/laminas-db/ (at least) are pointing to the `zenfdframework` organization instead of `laminas` one.

Also, the way the code snippets are displayed is really not readable:
![image](https://user-images.githubusercontent.com/224733/71656612-2decc200-2d3c-11ea-8f9f-d0c3165ddd50.png)

**Comment by michalbundyra** [comment]
See: https://github.com/laminas/documentation-theme/pull/2

**Comment by trasher** [comment]
Thanks for the pointer @michalbundyra!

Also see https://github.com/laminas/laminas-db/issues/31 for the contrast issue.
