### ISSUE TITLE
Bug with zend-db

### ISSUE THREAD

**Issue by tomvisions** [laminas/laminas-db#35]
Bug fix zendframework/zend-db#383 (https://github.com/zendframework/zend-db/commit/c11bffd804fcbbe9e72a6019c1d04c08201329ed) causes some big issues on our site. 

We have a prepare statement doing

$statement->prepare('SET SESSION group_concat_max_len=:value');
$statement->execute([':value' => 655350]);

from the code in execute function, it now interprets the number as a string instead of an integer
wondering how to interpret the number as a integer again. let me know if you have any questions

**Comment by happydude** [comment]
This change also breaks using a parameter with LIMIT

```php
$statement->prepare('SELECT `id` FROM `session` WHERE expires > ? LIMIT ?');
$statement->execute([1,2]);
```

generates invalid
```sql
SELECT `id` FROM `session` WHERE expires > '1' LIMIT '2'
```

If I set the driver option of \PDO::ATTR_EMULATE_PREPARES => false then it works
```sql
SELECT `id` FROM `session` WHERE expires > ? LIMIT ?
SELECT `id` FROM `session` WHERE expires > '1' LIMIT 2
```

That doesn't work for the original SET SESSION example above, I read that php falls back to emulation for things that mysql can't prepare, I'm guessing that is the reason.

**Comment by developer-devPHP** [comment]
I also have same problem with **MySQL** ``LIMIT`` ``OFFSET``

**Comment by kynx** [comment]
Another usage that will break: `WHERE bitmask_col & ?`

I can’t see anything else but to revert the change and advise users to cast to a string if that’s the behaviour they’re looking for. 

Someone going to get the glory of a PR?

**Comment by happydude** [comment]
It was not obvious to me looking at the original bug https://github.com/zendframework/zend-db/issues/383 how 123456 = 123456a.

The query generated with 2.10.0 was
```sql
 SELECT * FROM `test_table` WHERE `name` = 123456
```

That query actually matches both rows due to type conversion in mysql, but that was not apparent because the code only prints out the first row.

**Comment by andreasschroth** [comment]
> It was not obvious to me looking at the original bug [zendframework/zend-db#383](https://github.com/zendframework/zend-db/issues/383) how 123456 = 123456a.
> 
> The query generated with 2.10.0 was
> 
> ```sql
>  SELECT * FROM `test_table` WHERE `name` = 123456
> ```
> 
> That query actually matches both rows due to type conversion in mysql, but that was not apparent because the code only prints out the first row.

Exactly. Nothing wrong here from this package, it's the developer's task / choice to pass the correct datatype here. If he wants an exact match with a string, he needs to pass a string and type-cast it before.
