### ISSUE TITLE
Boolean values in the Mysql Statements cause execute to silently fail

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#46]
- [X] I was not able to find an [open](https://github.com/zendframework/zend-db/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-db/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [X] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

So I've been hitting my head on the wall for the entire day on this and I just managed to figure it out. 

Although in theory zend-db is properly handling boolean values in the `Statement:: bindParametersFromContainer()` it appears that there is a bug lying in PHP which is still there in  7.1 and 7.2 (https://bugs.php.net/bug.php?id=38546). 

Passing `PDO::PARAM_BOOL` in the `bindParam` causes the `PDOStatement::execute()` to **silently** `return false` and not throw any exception, even though `PDO::ATTR_ERRMODE` is set to `PDO::ERRMODE_EXCEPTION`

The reason I'm opening this is to bring it to your attention and perhaps discuss if booleans should be treated as integers until a fix is available

### Code to reproduce the issue

```php
$sql = new Sql($this->getDbAdapter());

$insert = $sql->insert()
    ->into('Table')
    ->values([ 'field' => true ]);

try {
   $insertStatement = $sql->prepareStatementForSqlObject($insert);
   $result = $insertStatement->execute();
} catch( \Exception $e ) {
   // will never get here
}

// this is false
return ( $result && $result->getAffectedRows() > 0 );
```

### Expected results

The statement should get prepared in the mysql and then get executed. However that is not the case. Looking into mysql's general_log_file one can see the statement being prepared but never executed.

### Actual results

`PDOStatement::execute()` returns false and no exception was thrown thus the only way to detect that the query failed is via the `getAffectedRows()` but there is absolutely no indication on what went wrong.

---

Originally posted by @twmobius at https://github.com/zendframework/zend-db/issues/323

**Comment by michalbundyra** [comment]
@twmobius I tried reproducing this and couldn't. It works as expected on:
zend-db 2.9.3 
PHP 7.1.20
MariaDB 10.1.29

Can you state what versions this isn't working on please.

---

Originally posted by @shaunfreeman at https://github.com/zendframework/zend-db/issues/323#issuecomment-406823351

**Comment by michalbundyra** [comment]
Sorry completely missed this.

It's been a while but I believe this happened on PHP 7.2.6,  mySQL 5.7.22 and zend-db 2.9.3. I will remove my workaround and see if I can still reproduce it

---

Originally posted by @twmobius at https://github.com/zendframework/zend-db/issues/323#issuecomment-421738145

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
