### ISSUE TITLE
Prepared query wrong number of parameter on 2.9.3

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#47]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-db/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-db/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

Trying to execute a prepared query with named parameters. Works well with 2.9.2 but fails on 2.9.3.

### Code to reproduce the issue

Something like:
```php
$insert = $zdb->sql->insert(self::TABLE);
$insert->values(
    array(
        'name'  => ':name',
        'value'  => ':value'
    )
);
$stmt = $zdb->sql->prepareStatementForSqlObject($insert);

foreach ($values as $k => $v) {
    $stmt->execute(
        array(
            'name' => $k,
            'value' => $v
        )
    );
}
```

### Expected results

Query success.

### Actual results

Fails with the following exception:
```
==> An exception has been thrown in file tests/units/Preferences.php on line xx:
==> PDOException: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens in vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:239
==> Stack trace:
==> #0 vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php(239): PDOStatement->execute()
==> #1 lib/Preferences.php(310): Zend\Db\Adapter\Driver\Pdo\Statement->execute(Array)
[...]
```

Array passed to `Statement::execute()` looks like:
```php
array(
    'name' => 'lang',
    'value' => 'en_US'
)
```

Thank you.

---

Originally posted by @trasher at https://github.com/zendframework/zend-db/issues/322

**Comment by michalbundyra** [comment]
The problem persists with zend-db 2.10.0.

---

Originally posted by @guillomovitch at https://github.com/zendframework/zend-db/issues/322#issuecomment-537608176

**Comment by trasher** [comment]
Problem seems to be named parameters, globally. This is still present with latest release.

Another example:
```
$update = $sql->update('mytable');
$update->set(
    array(
        'value'  => ':value'
    )
)->where->equalTo('name', ':name');
$stmt = $sql->prepareStatementForSqlObject($update);
```
In that example, trying to execute the statement with this array will fail:
```
array(
    ':name' => 'a name',
   ':value' => 'a value'
)
```
But that will works with:
```
array(
    ':c_0' => 'a name',
    ':where1' => 'a value'
)
```
or
```
array(
    'a name',
    'a value'
)
```

I really do not know if the problem is in `prepareStatementForSqlObject`, or in the parameters container that should to a kind of mapping.

**Comment by froschdesign** [comment]
Please create a pull request with an unit test which illustrates the problem.

Thanks in advance!

**Comment by trasher** [comment]
I can take a look, but as I've said, I do not know what is expected here. Should the query be like:
1- `UPDATE mytable SET value = :value WHERE name = :name`
or
2- `UPDATE mytable SET value = :c_0 WHERE name = :where1`

**Comment by trasher** [comment]
OK, I've added a case to reproduce in integration tests. See #160

**Comment by trasher** [comment]
Maybe linked to https://github.com/zendframework/zend-db/issues/35
