### ISSUE TITLE
Use postgres-specific tables to read database schema

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#48]
Fixes performance issues noted in #199.

On my production server, the original query took 22 seconds to retrieve 272 rows. This new query takes 204ms and retrieves the same rows.

This is based off @alextech query in #199 and adapted to be a drop-in replacement (it returns the correct values for check_option and is_updatable.

Closes #199

---

Originally posted by @mat128 at https://github.com/zendframework/zend-db/pull/321

**Comment by michalbundyra** [comment]
@mat128 thank for the PR, it looks very good! We need to provide a test for this change. We have a `test/integration` folder where we can test PostgreSQL using Travis CI, see this [database test configuration](https://github.com/zendframework/zend-db/blob/master/.ci/pgsql_fixtures.sh).
Have a look and let me know if you need assistance adding this integration test, thanks!

---

Originally posted by @ezimuel at https://github.com/zendframework/zend-db/pull/321#issuecomment-411051504

**Comment by michalbundyra** [comment]
This repository has been moved to laminas/laminas-db. If you feel that this patch is still relevant, please re-open against that repository, and reference this issue. To re-open, we suggest the following workflow:
 - Squash all commits in your branch (`git rebase -i origin/{branch}`)
 - Make a note of all changed files (`git diff --name-only origin/{branch}...HEAD
 - Run the laminas/laminas-migration tool on the code.
 - Clone laminas/laminas-db to another directory.
 - Copy the files from the second bullet point to the clone of laminas/laminas-db.
 - In your clone of laminas/laminas-db, commit the files, push to your fork, and open the new PR.
 We will be providing tooling via laminas/laminas-migration soon to help  automate the process.

---

Originally posted by @weierophinney at https://github.com/zendframework/zend-db/pull/321#issuecomment-570001145

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
