### ISSUE TITLE
SQL column alias bug

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#51]
....$select...->join('vendors', 'vendors.id = campaigns_vendors.vendor_id', ['vendor_id'=>'id', 'vendor_daily_limit'=>'daily_limit'], $select::JOIN_LEFT)

When I query this select object I get the following error: "Not a valid magic property for this object"
When I rename the column alias to anything else but 'vendor_daily_limit' the error goes away. 
When I print the produced SQL and run it via phpMyadmin or Bench then the query executes perfectly.

Very bizarre error and no indication of what is causing it.

---

Originally posted by @TradeSharer at https://github.com/zendframework/zend-db/issues/317

**Comment by michalbundyra** [comment]
I have no luck to reproduce that error on my local env)

Could you please add more information, may be table structure or scope code ?)

---

Originally posted by @tptrixtop at https://github.com/zendframework/zend-db/issues/317#issuecomment-388212403

**Comment by michalbundyra** [comment]
you should can do something like this: 

```php
use Zend\Db\Sql\Predicate\Expression;

$select->join(
     'vendors', 
     'vendors.id = campaigns_vendors.vendor_id', 
     [
         'vendor_id'          => new Expression('vendors.id'),
         'vendor_daily_limit' => new Expression('vendors.daily_limit'),
      ],
      $select::JOIN_LEFT
);
```

---

Originally posted by @samsonasik at https://github.com/zendframework/zend-db/issues/317#issuecomment-388593562

**Comment by michalbundyra** [comment]
It turns out I was looking at the wrong code.
The error "Not a valid magic property for this object" is produced when you call a non-existing method on the Sql object i.e. $sql->join(....)->equalTo(....) - equalTo is a method of Where and not Sql, since ZF uses overloading for this, the error message is not obvious.
A better message would be something like: "method equalTo not defined for Sql"

Sorry for wasting your time.

---

Originally posted by @TradeSharer at https://github.com/zendframework/zend-db/issues/317#issuecomment-388609669

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
