### ISSUE TITLE
HydratingResultSet current method DocBlock @return

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#52]
- [X] I was not able to find an [open](https://github.com/zendframework/zend-db/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-db/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [X] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

HydratingResultSet `current()` method is specified in the DocBlock block that is should return an object as seen here:

https://github.com/zendframework/zend-db/blob/ec0e9b51a09fc44f81af77fb949808fb4552c1cf/src/ResultSet/HydratingResultSet.php#L93

The method however could also return a boolean `false`:

https://github.com/zendframework/zend-db/blob/ec0e9b51a09fc44f81af77fb949808fb4552c1cf/src/ResultSet/HydratingResultSet.php#L103

I am guessing that the best solution for this, as well as possibly other locations to change the boolean `false` to `null` and mark the method to return `?object` instead

---

Originally posted by @twmobius at https://github.com/zendframework/zend-db/issues/316

**Comment by michalbundyra** [comment]
@twmobius It is indeed should returns `null` on no data for consistency I think. I created PR #325 for it.

---

Originally posted by @samsonasik at https://github.com/zendframework/zend-db/issues/316#issuecomment-401984271

**Comment by samsonasik** [comment]
already fixed by https://github.com/laminas/laminas-db/pull/39 . I am closing it.
