### ISSUE TITLE
Add mysqli connection flags to mysqli_real_connect 

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#53]
The Mysqli driver doesn't allow setting of flags passed into mysqli_real_connect.

- [x] Are you fixing a bug?
  - [x] Detail how the bug is invoked currently.

In some instances (like MySQL and PHP on Azure) MYSQLI_SSL_CLIENT needs to be set.

    'params' => [
        'host' => 'xxxx.mysql.database.azure.com',
        'port' => 3306,
        'user' => 'xxxx@xxxxx',
        'password' => 'xxxxx',
        'dbname' => 'xxxx',
        'charset' => 'utf8',
        'use_ssl' => true,
        'ssl_ca' => 'xxxxx/certs/BaltimoreCyberTrustRoot.crt.pem',
        'driver_options' => [ ]
    ]

  - [x] Detail the original, incorrect behavior.

This calls ``$this->resource->ssl_set($clientKey, $clientCert, $caCert, $caPath, $cipher);`` to configure the SSL options, but no flag is set on mysqli_real_connect. Connection to Azure subsequently fails with 'SSL connection is required' 

  - [x] Detail the new, expected behavior.

Driver should allow connecting as illustrated in azure documentation at https://docs.microsoft.com/en-us/azure/mysql/howto-configure-ssl .

Added 'flags' config key to driver_options to support the setting of flags into mysqli_real_connect. This lets users supply MYSQLI_CLIENT_SSL and other connection flags as indicated on http://www.php.net/manual/en/mysqli.real-connect.php

    'params' => [
        'host' => 'xxxx.mysql.database.azure.com',
        'port' => 3306,
        'user' => 'xxxx@xxxxx',
        'password' => 'xxxxx',
        'dbname' => 'xxxx',
        'charset' => 'utf8',
        'use_ssl' => true,
        'ssl_ca' => 'xxxxx/certs/BaltimoreCyberTrustRoot.crt.pem',
        'driver_options' => [ 
            'flags' => MYSQLI_CLIENT_SSL 
        ]
    ]

---

Originally posted by @kris-sum at https://github.com/zendframework/zend-db/pull/314

**Comment by michalbundyra** [comment]
Is anyone available to review this? @ezimuel @weierophinney ?

---

Originally posted by @kris-sum at https://github.com/zendframework/zend-db/pull/314#issuecomment-387320335

**Comment by michalbundyra** [comment]
@kris-sum We need test case for this change.

---

Originally posted by @michalbundyra at https://github.com/zendframework/zend-db/pull/314#issuecomment-387351079

**Comment by michalbundyra** [comment]
@webimpress Any test case would require setting up SSL on the MySQL end - I can't see a way I can do that with the current integration test setup?

---

Originally posted by @kris-sum at https://github.com/zendframework/zend-db/pull/314#issuecomment-387355515

**Comment by michalbundyra** [comment]
@kris-sum mock `resource`, pass it into the constructor and check if calls are with proper values/flags. Seems to be doable.

---

Originally posted by @michalbundyra at https://github.com/zendframework/zend-db/pull/314#issuecomment-387359249

**Comment by michalbundyra** [comment]
@kris-sum can you provide the unit test as suggested by @webimpress ? Thanks.

---

Originally posted by @ezimuel at https://github.com/zendframework/zend-db/pull/314#issuecomment-392775548

**Comment by michalbundyra** [comment]
This repository has been moved to laminas/laminas-db. If you feel that this patch is still relevant, please re-open against that repository, and reference this issue. To re-open, we suggest the following workflow:
 - Squash all commits in your branch (`git rebase -i origin/{branch}`)
 - Make a note of all changed files (`git diff --name-only origin/{branch}...HEAD
 - Run the laminas/laminas-migration tool on the code.
 - Clone laminas/laminas-db to another directory.
 - Copy the files from the second bullet point to the clone of laminas/laminas-db.
 - In your clone of laminas/laminas-db, commit the files, push to your fork, and open the new PR.
 We will be providing tooling via laminas/laminas-migration soon to help  automate the process.

---

Originally posted by @weierophinney at https://github.com/zendframework/zend-db/pull/314#issuecomment-570001147

**Comment by demiankatz** [comment]
@webimpress, @michalbundyra, as @kris-sum pointed out above, PR #169 should resolve this issue. What needs to be done to get that PR merged? Happy to help in any way I can, as this fix would be very helpful to have!

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
