### ISSUE TITLE
Reconnect on lost DB connection

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#55]
This functionality allow to enable & configure reconnect functionality using `options` parameter in adapter.

When you are creating adapter for `mysqli`:

```php
$adapter = new Adapter([
    'driver' => 'Mysqli',
    'database' => '',
    'username' => '',
    'password' => '',
    'options' => [
        'reconnect_tries' => 3
    ]
]);
```

You can specify `reconnect_tries` and if during your work connect will be lost adapter will try automatically reconnect to server.

Fix for #302 

---

Originally posted by @tptrixtop at https://github.com/zendframework/zend-db/pull/307

**Comment by michalbundyra** [comment]
1.  Needs addition to documentation about new 'reconnect_tries' option.
2.  Needs tests
3.  being a general DB tool, having a feature like this only favoring MySQL ignoring other engines does not make the library look good.  At the least, if not have the ability to apply to all supported engines, make a statement in documentation that so far only available in MySQL and maintainer could add "help wanted" tag for other databases.

---

Originally posted by @alextech at https://github.com/zendframework/zend-db/pull/307#issuecomment-370238937

**Comment by michalbundyra** [comment]
I will  try to add support for other engines soon.

I know about unit tests) but when i have written that code i had no idea how to test that functionality)

For now i have some ideas, i will try)

---

Originally posted by @tptrixtop at https://github.com/zendframework/zend-db/pull/307#issuecomment-370239581

**Comment by michalbundyra** [comment]
Ok, thats fine :) Does seem like a challenge to test!

For documentation, I actually meant adding entry into docs/book markdown sources.

---

Originally posted by @alextech at https://github.com/zendframework/zend-db/pull/307#issuecomment-370239913

**Comment by michalbundyra** [comment]
Ah, get it) i will add docs about that option to adapter.md

---

Originally posted by @tptrixtop at https://github.com/zendframework/zend-db/pull/307#issuecomment-370240069

**Comment by michalbundyra** [comment]
@tptrixtop we need some unit test for this new feature. Consider that now we have also [integration tests](https://github.com/zendframework/zend-db/tree/master/test/integration) available.

---

Originally posted by @ezimuel at https://github.com/zendframework/zend-db/pull/307#issuecomment-378224810

**Comment by michalbundyra** [comment]
Sure, I am now working on same functionality for postgresql, it's almost finished and after i will try add same functionality for MS SQL and i will commit unit tests for all of that changes)

---

Originally posted by @tptrixtop at https://github.com/zendframework/zend-db/pull/307#issuecomment-378257125

**Comment by michalbundyra** [comment]
@tptrixtop we still need tests for this feature.

---

Originally posted by @ezimuel at https://github.com/zendframework/zend-db/pull/307#issuecomment-411068109

**Comment by michalbundyra** [comment]
@ezimuel I know sir, i am working on it, right now)

---

Originally posted by @tptrixtop at https://github.com/zendframework/zend-db/pull/307#issuecomment-411078060

**Comment by michalbundyra** [comment]
This repository has been moved to laminas/laminas-db. If you feel that this patch is still relevant, please re-open against that repository, and reference this issue. To re-open, we suggest the following workflow:
 - Squash all commits in your branch (`git rebase -i origin/{branch}`)
 - Make a note of all changed files (`git diff --name-only origin/{branch}...HEAD
 - Run the laminas/laminas-migration tool on the code.
 - Clone laminas/laminas-db to another directory.
 - Copy the files from the second bullet point to the clone of laminas/laminas-db.
 - In your clone of laminas/laminas-db, commit the files, push to your fork, and open the new PR.
 We will be providing tooling via laminas/laminas-migration soon to help  automate the process.

---

Originally posted by @weierophinney at https://github.com/zendframework/zend-db/pull/307#issuecomment-570001148

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
