### ISSUE TITLE
Reconnect on lost DB connection with PDO_MYSQL

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#56]
I am using php for long running scripts as a RabbitMq message comsumer. Messages can have DB access implemented as ZF3 / zend-db Tablegateway. The DB connection used is PDO_MYSQL.
In case DB connection is killed (MYSQL_CONNECTION_TIMEOUT or other), AbstractTableGateway throws an error (HY000 - 2006 - MySQL server has gone away) when trying to execute a statement against the closed connection.

I expect that Tablegateway / Adapter / db Driver is smart enough to handle lost connection and reconnect or at least handle "unconnected" state and connect (again).

### Code to reproduce the issue

* use some Tablegateway connected via PDO_MYSQL in a long running loop
* while the loop runs, go to the MySQL-Server and kill the connection manually
* you will get "HY000 - 2006 - MySQL server has gone away" in Tablegateway / Adapter / db Driver. 

### Expected results

when the DB connection is lost the DB managing objects should be able to connect again to the DB again as they did initially.

### Actual results

* when the DB connection is lost the DB managing objects are not able to connect again. An error is thrown: "HY000 - 2006 - MySQL server has gone away" in Tablegateway / Adapter / db Driver. 

---

Originally posted by @finalJustize at https://github.com/zendframework/zend-db/issues/302

**Comment by michalbundyra** [comment]
I had the same prob. I had to catch the PDOException and do manually: 

`$this->adapter->getDriver()->getConnection()->disconnect();`

so next time the worker tries to consume a message it will create a new connection. 

In `doctrine/dbal` they've implemented a pingable connection to verify the connection: [Connection.php](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Connection.php#L1685)
Maybe it makes sense for this case.

---

Originally posted by @monteiro at https://github.com/zendframework/zend-db/issues/302#issuecomment-383131747

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
