### ISSUE TITLE
Add clear docblock to all classes and interfaces

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#58]
Many classes and interfaces don't have docblocks. A developer and the IDE is not able to know which data should returned. Best example is the TableGatewayInterface.

Can I send an PR for this?

---

Originally posted by @fadoe at https://github.com/zendframework/zend-db/issues/297

**Comment by michalbundyra** [comment]
@fadoe 
That would be great!

---

Originally posted by @froschdesign at https://github.com/zendframework/zend-db/issues/297#issuecomment-354263210

**Comment by michalbundyra** [comment]
I created a PR, but it is not completed now. I have for example a question about the StatementContainerInterface. Where is the best place for this questions? This issue or the pull request?

---

Originally posted by @fadoe at https://github.com/zendframework/zend-db/issues/297#issuecomment-354266937

**Comment by michalbundyra** [comment]
I have a question to the DriverFeatureInterface.

The addFeature in the interface describes the feature as mixed, in Driver\Pdo\Pdo as AbstractFeature. getFeature returns in Driver\Pdo\Pdo AbstractFeature or false (see docblock). Is this a difference between the interface and the extended Pdo class? I think in the DriverFeatureInterface should it also AbstractFeature.

---

Originally posted by @fadoe at https://github.com/zendframework/zend-db/issues/297#issuecomment-354453802

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
