### ISSUE TITLE
Incorrect Sql Expression parameters when passing zero in the constructor

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-db#6]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-db/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-db/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

I am trying to create an expression that has zero as the parameter value. However, the parameters incorrectly show as empty.

### Code to reproduce the issue

```php
$expr = new \Zend\Db\Sql\Expression('?', '0');
print_r($expr->getParameters());
```

### Expected results

It prints "0"

### Actual results

It prints empty array

### Proposed fix

https://github.com/zendframework/zend-db/blob/master/src/Sql/Expression.php#L59

In `Zend\Db\Sql\Expression`, update the constructor to explicitly check for '0' when setting parameters

```php
if ($parameters || $parameters === '0') {
     $this->setParameters($parameters);
}
```

---

Originally posted by @albertor24 at https://github.com/zendframework/zend-db/issues/381

**Comment by weierophinney** [comment]
@albertor24 Please submit PR and add test to cover your case 👍 

---

Originally posted by @michalbundyra at https://github.com/zendframework/zend-db/issues/381#issuecomment-508366768

**Comment by samsonasik** [comment]
I seems already fixed. I tried it:

```bash
➜  laminas-db git:(master) php -a
Interactive shell

php > include 'vendor/autoload.php';
php > $expr = new \Zend\Db\Sql\Expression('?', '0');
php > print_r($expr->getParameters());
0
```

I'm closing it.
