### ISSUE TITLE
join colums not reset

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#60]
https://github.com/zendframework/zend-db/blob/748f065ab8e64ab66213182a671513e9499957bc/src/Sql/Select.php#L426

---

Originally posted by @hemengze at https://github.com/zendframework/zend-db/issues/279

**Comment by michalbundyra** [comment]
```php
case self::COLUMNS:
    $this->columns = array();
    foreach ($this->joins as &$join){
        $join['columns'] = [];
    }
break;
```

---

Originally posted by @hemengze at https://github.com/zendframework/zend-db/issues/279#issuecomment-343467755

**Comment by michalbundyra** [comment]
@hemengze 
The entire `joins` property is reset:
https://github.com/zendframework/zend-db/blob/748f065ab8e64ab66213182a671513e9499957bc/src/Sql/Select.php#L428-L430

---

Originally posted by @froschdesign at https://github.com/zendframework/zend-db/issues/279#issuecomment-343479220

**Comment by michalbundyra** [comment]
when work with paginator, sql like this:
```sql
select count(*), b.id, b.created_at from A as a inner join B as b on A.bid = b.id limit 1;
```

---

Originally posted by @hemengze at https://github.com/zendframework/zend-db/issues/279#issuecomment-343480377

**Comment by michalbundyra** [comment]
@hemengze 
> when work with paginator, sql like this:

Sorry, I don't understand. Please describe your problem with full sentence. This will help.
Thanks!

Maybe you mean this cloning:

https://github.com/zendframework/zend-paginator/blob/master/src/Adapter/DbSelect.php#L142-L145



---

Originally posted by @froschdesign at https://github.com/zendframework/zend-db/issues/279#issuecomment-343492775

**Comment by michalbundyra** [comment]
@froschdesign thank you.
When I'm join a table with columns, reset the columns, the join columns still exists
```php
$select = (new (Select))->join('B b', 'a.bid = b.id', 'id, created_at');
$select->reset(Select::COLUMNS);
$select->reset(Select::LIMIT);
$select->reset(Select::OFFSET);
$select->reset(Select::ORDER);
```
the columns  `b.id, b.created_at` already exists

---

Originally posted by @hemengze at https://github.com/zendframework/zend-db/issues/279#issuecomment-343494301

**Comment by michalbundyra** [comment]
can something like this solve this problem?

```
public static function getCountSelect(Select $originalSelect, $fieldCountCriteria="id" )
	{
		$select = clone $originalSelect;
		$select->reset(Select::COLUMNS);
		$select->reset(Select::LIMIT);
		$select->reset(Select::OFFSET);
		$select->reset(Select::ORDER);
                $select->reset(Select::GROUP);
		/** @var Join $joins */
		$joins = $select->joins->getJoins();

		$select->reset(Select::JOINS);
		foreach ($joins as $key => $join) {
			//re add join without cols
			$type = $join["type"];
			$select->join($join["name"], $join["on"], [], $type);
		}

		$select->columns(["total" => new Expression("count(distinct($fieldCountCriteria))")]);

		return $select;
	}
```

It will re-init the joins without any column set.
It seems working for my situation... try at your own risk :smiley: 

---

Originally posted by @marc0n3 at https://github.com/zendframework/zend-db/issues/279#issuecomment-389444808

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
