### ISSUE TITLE
UTF8 should be supported in regex

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#61]
[https://github.com/zendframework/zend-db/blob/master/src/Adapter/Platform/AbstractPlatform.php](url)
line 44
```PHP
$parts = preg_split(
            '/([^0-9,a-z,A-Z$_:])/i',
            $identifier,
            -1,
            PREG_SPLIT_DELIM_CAPTURE | PREG_SPLIT_NO_EMPTY
        );
```
I run into problem because pattern '/([^0-9,a-z,A-Z$_:])/i', doesn't support utf8.

I think pattern modifier 'u' should be added.
'/([^0-9,a-z,A-Z$_:])/iu'

---

Originally posted by @ares333 at https://github.com/zendframework/zend-db/issues/277

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
