### ISSUE TITLE
Allow invokable classes as predicate (solves #270)

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#62]
This PR solves #270 .
Predicates can now created from an invokable class. Like closures, the new predicates should directly added to the Select, Where or Update instance.

---

Originally posted by @heyphilllie at https://github.com/zendframework/zend-db/pull/272

**Comment by michalbundyra** [comment]
@Ocramius the status of this one is hard... do we have someone willing to update this library for PHP 7? Or at a minimum get the travis and composer config moving in the right direction?

---

Originally posted by @mwillbanks at https://github.com/zendframework/zend-db/pull/272#issuecomment-338092310

**Comment by michalbundyra** [comment]
IMO we should hold back new features until 7.1 is the minimum version. Everything we add without explicit type declarations will just come back like a boomerang.

---

Originally posted by @Ocramius at https://github.com/zendframework/zend-db/pull/272#issuecomment-338092573

**Comment by michalbundyra** [comment]
@Ocramius I tagged this as 3.0 release.

---

Originally posted by @ezimuel at https://github.com/zendframework/zend-db/pull/272#issuecomment-346623625

**Comment by michalbundyra** [comment]
@Ocramius I was wondering if you could go into detail how explicit type declarations would help in this situation or conversely if there is any foreseeable boomerang?

---

Originally posted by @baileylo at https://github.com/zendframework/zend-db/pull/272#issuecomment-363193867

**Comment by michalbundyra** [comment]
This repository has been moved to laminas/laminas-db. If you feel that this patch is still relevant, please re-open against that repository, and reference this issue. To re-open, we suggest the following workflow:
 - Squash all commits in your branch (`git rebase -i origin/{branch}`)
 - Make a note of all changed files (`git diff --name-only origin/{branch}...HEAD
 - Run the laminas/laminas-migration tool on the code.
 - Clone laminas/laminas-db to another directory.
 - Copy the files from the second bullet point to the clone of laminas/laminas-db.
 - In your clone of laminas/laminas-db, commit the files, push to your fork, and open the new PR.
 We will be providing tooling via laminas/laminas-migration soon to help  automate the process.

---

Originally posted by @weierophinney at https://github.com/zendframework/zend-db/pull/272#issuecomment-570001155

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
