### ISSUE TITLE
Allow Invokable Objects For `$where` parameters in AbstractTableGateway

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#63]
Currently, the `$where` parameter in `AbstractTableGateway::select`, `AbstractTableGateway::update`, and `AbstractTableGateway::delete` will accept Closures, but not invokable classes. It would be nice if it were possible expand the allowed parameters types to include invokable classes.

The following code should allow it. I was hoping to replace with `is_callable($where)`, but that would return `true` for cases where `$where` couldn't be executed using `$where($select);`, e..g `[ new\DateTime, 'format']`.

```php
if ($where instanceof \Closure || (is_object($where) && is_callable($where))) {
    $where($select);
} elseif ($where !== null) {
    $select->where($where);
}
```

---

Originally posted by @baileylo at https://github.com/zendframework/zend-db/issues/270

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
