### ISSUE TITLE
explicitly display mysqli error

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#64]
Minor change to show mysqli errno and error explicitly. Without this, mysqli errors do not get shown in some debuggers when preparing sql statements, for example [whoops](https://filp.github.io/whoops/). 

Here is an example with whoops before
![original_schema_error](https://user-images.githubusercontent.com/16896053/31135530-2fbad6f0-a85d-11e7-8c78-b03f39f2c0e3.png)

and after the change.
![schema_error_corrected](https://user-images.githubusercontent.com/16896053/31135535-32ec4958-a85d-11e7-9b11-d8351771d2b5.png)

I think some components already use this style, for example [zend-http/src/Client/Adapter/Socket.php](https://github.com/zendframework/zend-http/blob/master/src/Client/Adapter/Socket.php#L278) line 278. 

---

Originally posted by @ConorSheehan1 at https://github.com/zendframework/zend-db/pull/269

**Comment by michalbundyra** [comment]
@mwillbanks I'm having some trouble creating a mock connection to a database. I've pushed up my attempt in the last commit. Sorry, it's a bit messy. I tried following the Pdo test setup as an example. Could you give me some suggestions on how to create an appropriate mock or stub for the db connection?

---

Originally posted by @ConorSheehan1 at https://github.com/zendframework/zend-db/pull/269#issuecomment-338674843

**Comment by michalbundyra** [comment]
This repository has been moved to laminas/laminas-db. If you feel that this patch is still relevant, please re-open against that repository, and reference this issue. To re-open, we suggest the following workflow:
 - Squash all commits in your branch (`git rebase -i origin/{branch}`)
 - Make a note of all changed files (`git diff --name-only origin/{branch}...HEAD
 - Run the laminas/laminas-migration tool on the code.
 - Clone laminas/laminas-db to another directory.
 - Copy the files from the second bullet point to the clone of laminas/laminas-db.
 - In your clone of laminas/laminas-db, commit the files, push to your fork, and open the new PR.
 We will be providing tooling via laminas/laminas-migration soon to help  automate the process.

---

Originally posted by @weierophinney at https://github.com/zendframework/zend-db/pull/269#issuecomment-570001157

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
