### ISSUE TITLE
Adding a fix for #267.

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#65]
In #267 I described the incorrect behaviour, when generating DDLs with characters in name that are used for escaping on different plattforms. This is an attempt to fix it.
I tested the behaviour and it corrects the script generation with the base (PostgreSQL, SQLite) and MySQL escaping behaviour.

MSSQL seems to behave like standard despite having separate escaping, so I didn't touch it. I was able to test with driver `Pdo_SqlServer`, perhaps it uses the escaping with brackets, if `Sqlsrv` driver is used, but I couldn't test it, because I don't have the corresponding extension installed. I get the RuntimeException with message `The Sqlsrv extension is required for this adapter but the extension is not loaded`. @alextech Can you test the example in #267 and add the [] brackets to every named element? If it uses the brackets for escaping and is wrong, is it fixed, if you change in `Zend\Db\Adapter\Platform\SqlSserver` $quoteIdentifierTo to
```php
    protected $quoteIdentifierTo = '[]';
```
At least from my tests SQL Management Studio escapes the opening bracket in names by adding the closing bracket to it, when I generate a CREATE TABLE script.

---

Originally posted by @rarog at https://github.com/zendframework/zend-db/pull/268

**Comment by michalbundyra** [comment]
I'll work on unit test next week. Thx for the first review!

---

Originally posted by @rarog at https://github.com/zendframework/zend-db/pull/268#issuecomment-338134118

**Comment by michalbundyra** [comment]
@mwillbanks I finally found time to add the unit tests. Are they ok in that form?

---

Originally posted by @rarog at https://github.com/zendframework/zend-db/pull/268#issuecomment-385200118

**Comment by michalbundyra** [comment]
This repository has been moved to laminas/laminas-db. If you feel that this patch is still relevant, please re-open against that repository, and reference this issue. To re-open, we suggest the following workflow:
 - Squash all commits in your branch (`git rebase -i origin/{branch}`)
 - Make a note of all changed files (`git diff --name-only origin/{branch}...HEAD
 - Run the laminas/laminas-migration tool on the code.
 - Clone laminas/laminas-db to another directory.
 - Copy the files from the second bullet point to the clone of laminas/laminas-db.
 - In your clone of laminas/laminas-db, commit the files, push to your fork, and open the new PR.
 We will be providing tooling via laminas/laminas-migration soon to help  automate the process.

---

Originally posted by @weierophinney at https://github.com/zendframework/zend-db/pull/268#issuecomment-570001158

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
