### ISSUE TITLE
Escaping of table, column and index name is wrong

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#66]
It seems that escaping is wrong for at least DDLs, I didn't test SELECT and other commands.
~~It goes wrong with (MySQL) and without (SQLite) decorators.~~ The example for SQLite is flawed in terms of syntax, as the basic index creation isn't supported within CREATE TABLE command, but this should be a separate task similar to #163. This bug is only for the escaping issue.
Instead of just doubling the escape character there seems to be done some wrong escaping which is additionally run multiple times.

I tried following:
```php
$table = new CreateTable('t\'e"s`t');
$table->addColumn(new BigInteger('t\'e"s`tCol'))
    ->addColumn(new BigInteger('t\'e"s`tCol2'))
    ->addConstraint(new Constraint\PrimaryKey('t\'e"s`tCol'));
    ->addConstraint(new Index('t\'e"s`tCol2', 't\'e"s`tIndex'));
```

Expected output for MySQL:
```sql
CREATE TABLE `t'e"s``t` ( 
    `t'e"s``tCol` BIGINT NOT NULL AUTO_INCREMENT,
    `t'e"s``tCol2` BIGINT NOT NULL,
    PRIMARY KEY (`t'e"s``tCol`),
    INDEX `t'e"s``tIndex`(`t'e"s``tCol2`)
)
```
Actual output for MySQL:
```sql
CREATE TABLE `t'e"s``t` ( 
    `t``'``e``"``s``````tCol` BIGINT NOT NULL AUTO_INCREMENT,
    `t``'``e``"``s``````tCol2` BIGINT NOT NULL,
    PRIMARY KEY (`t``'``e``"``s``````tCol`),
    INDEX `t``'``e``"``s``````tIndex`(`t``'``e``"``s``````tCol2`)
)
```

Expected output for SQLite:
```sql
CREATE TABLE "t'e""s`t" ( 
    "t'e""s`tCol" BIGINT NOT NULL,
    "t'e""s`tCol2" BIGINT NOT NULL,
    PRIMARY KEY ("t'e""s`tCol"),
    INDEX "t'e""s`tCol2")
)
```
Actual output for SQLite:
```sql
CREATE TABLE "t'e's`t" ( 
    "t""'""e""'""s""`""tCol" BIGINT NOT NULL,
    "t""'""e""'""s""`""tCol2" BIGINT NOT NULL,
    PRIMARY KEY ("t""'""e""'""s""`""tCol"),
    INDEX "t""'""e""'""s""`""tIndex"("t""'""e""'""s""`""tCol2")
)
```

Not shown in the above example - the escaping also differs if for example the quotation mark is in the middle or in the beginning or end of the name.

Edit1:
Removed above the part with stylers, this problem is completely independent. At least the problem with table name misquotation can be fixed in `Zend\Db\Adapter\Platform\AbstractPlatform` class by changing $quoteIdentifierTo to
```php
    protected $quoteIdentifierTo = '""';
```
In the same time overwriting of $quoteIdentifierTo in `Zend\Db\Adapter\Platform\Postgresql` and overwriting of $quoteIdentifier and $quoteIdentifierTo in `Zend\Db\Adapter\Platform\Sqlite` could be removed.

Edit2:

The other problem with the broken column and index names comes from `function processExpression` in `Zend\Db\Sql\AbstractSql`
```php
                } elseif ($type == ExpressionInterface::TYPE_IDENTIFIER) {
                    $values[$vIndex] = $platform->quoteIdentifierInFragment($value);
```

`function quoteIdentifierInFragment` tries to split the string on all possible special chars, which breaks the column and index names. This parsing part is probably needed for true expressions where the code wasn't assembled by `Zend\Db` components but by hand in string. But in case of Ddl functions and probably all other classes like Select, that assemble the SQLs in correct way, this definitely breaks the functionality.
Either there should be special check for those classes (which I consider a dirty and too hardcoded way) or there should be introduced a new type named `ExpressionInterface::TYPE_IDENTIFIER_UNBREAKABLE` (or _UNSPLITTABLE or _WHATEVER) and be used by `function getExpression()` in all classes derived from `Zend\Db\Sql\Expression` and in that case `function processExpression` should call `quoteIdentifier`.

---

Originally posted by @rarog at https://github.com/zendframework/zend-db/issues/267

**Comment by michalbundyra** [comment]
Added notes about further analysis of the origin of this problem to the initial text.

---

Originally posted by @rarog at https://github.com/zendframework/zend-db/issues/267#issuecomment-332216894

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
