### ISSUE TITLE
Creating Index during CREATE TABLE doesn't work across different platforms

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#67]
Currently if I use DDL to add the basic (not unique) Index as constraint via CreateTable or AlterTable it does it via INDEX inside the CREATE TABLE statement like this:

```sql
CREATE TABLE "example" ( 
    "id" BIGINT NOT NULL,
    "anothercol" VARCHAR(10) NOT NULL,
    PRIMARY KEY ("id"),
    INDEX "example_index"("anothercol")
)
```

This works since ages on MySQL (which is probably the original and best supported part via LAMP environment and origin of ZF) and seemingly on MSSQL since SQL Server 2008 according to [documentation](https://msdn.microsoft.com/library/ms174979(v=sql.120).aspx). It's not supported by [SQLite](https://www.sqlite.org/lang_createtable.html), [PostgreSQL](https://www.postgresql.org/docs/9.6/static/sql-createtable.html), [IBM DB/2](https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.1.0/com.ibm.db2.luw.sql.ref.doc/doc/r0000927.html) and seemingly neither [Oracle](https://docs.oracle.com/database/122/SQLRF/CREATE-TABLE.htm#SQLRF01402).

However every database seems to support the separate CREATE INDEX command including MySQL and MSSQL.

This would be a working series of commands:

```sql
CREATE TABLE "example" ( 
    "id" BIGINT NOT NULL,
    "anothercol" VARCHAR(10) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX "example_index"("anothercol")
```

By rewriting the decorators this should be achievable and I could try contribute these parts of codes if such chaining of commands wouldn't contradict the guidelines. Alternatively additional DDL commands just for creating and dropping index would be needed to achieve the same. Perhaps this would even be a nice compromise. Creating the additional commands and later just call them from the decorators.

---

Originally posted by @rarog at https://github.com/zendframework/zend-db/issues/266

**Comment by michalbundyra** [comment]
Already did it at https://github.com/zendframework/zend-db/pull/231 A look over before I remove WIP would be helpful.

---

Originally posted by @alextech at https://github.com/zendframework/zend-db/issues/266#issuecomment-331982128

**Comment by michalbundyra** [comment]
Wrong one. That was SQL server compatibility in general. Index specifically I did at https://github.com/zendframework/zend-db/pull/163 which if goes through can be applied to SQL now that I have decorators for it too.

---

Originally posted by @alextech at https://github.com/zendframework/zend-db/issues/266#issuecomment-331995139

**Comment by michalbundyra** [comment]
Ah, thx. That fits more my expectations. The first look of it is good. I'll try apply it locally and test it tomorrow.

---

Originally posted by @rarog at https://github.com/zendframework/zend-db/issues/266#issuecomment-331998066

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
