### ISSUE TITLE
removed `getHelpers`

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-db#7]
method remained unused for 7 years and is bugged, see https://github.com/zendframework/zend-db/issues/379
 for details

---

Originally posted by @chris-kruining at https://github.com/zendframework/zend-db/pull/380

**Comment by weierophinney** [comment]
could someone merge?

---

Originally posted by @chris-kruining at https://github.com/zendframework/zend-db/pull/380#issuecomment-498295742

**Comment by weierophinney** [comment]
Even though it is not used, removal of a public method is a BC break. Since it causes no bugs or side effects it will be removed in next major.

---

Originally posted by @Xerkus at https://github.com/zendframework/zend-db/pull/380#issuecomment-498497491

**Comment by samsonasik** [comment]
I've created PR https://github.com/laminas/laminas-db/pull/170 for it.

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
