### ISSUE TITLE
Allow column names to contain any character

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#70]
In regards to issues #8 and #208 I've created a regex that will allow user to use any character as column name.
It will also keep functionality of allowing user to enter 'column as alias' as column name.
I've made an assumption that no one in right mind will have spaces on beginning or end of column name so they are ignored by regex.

---

Originally posted by @metalinspired at https://github.com/zendframework/zend-db/pull/249

**Comment by michalbundyra** [comment]
@metalinspired  unit tests are missing for this PR, can you add it? Testing is very important here because you proposed a regex and we need to validate all the possible cases (or at least the most common). Thanks!

---

Originally posted by @ezimuel at https://github.com/zendframework/zend-db/pull/249#issuecomment-310032080

**Comment by michalbundyra** [comment]
@ezimuel I wouldn't know where to begin. The regex if written so that all existing tests are passing and as you can see I failed three times before succeeding. If the regex fails it will throw an exception and worse that can happen is malformed SQL syntax which was original problem to begin with. Personally I think that some of the undocumented behavior for column names, which I mentioned in #208, should be removed thus eliminating need for this patch.

---

Originally posted by @metalinspired at https://github.com/zendframework/zend-db/pull/249#issuecomment-310037178

**Comment by michalbundyra** [comment]
@metalinspired I'll try to work on this PR adding the unit test, thanks anyway for your contribution!

---

Originally posted by @ezimuel at https://github.com/zendframework/zend-db/pull/249#issuecomment-310041327

**Comment by michalbundyra** [comment]
@ezimuel Glad I could help

---

Originally posted by @metalinspired at https://github.com/zendframework/zend-db/pull/249#issuecomment-310041650

**Comment by michalbundyra** [comment]
Hey @froschdesign @ezimuel - May we have any update for this? We need this in one of our products. So it'll be a great help if this PR gets merged. 

---

Originally posted by @bjgajjar at https://github.com/zendframework/zend-db/pull/249#issuecomment-538989084

**Comment by michalbundyra** [comment]
@bjgajjar Still we need unit test for these changes. If you can provide these it will speed up the release. Thanks.

---

Originally posted by @michalbundyra at https://github.com/zendframework/zend-db/pull/249#issuecomment-538993468

**Comment by michalbundyra** [comment]
@metalinspired - It seems like there is some issue here.

- When tried to add a field named with `@!#!12123123`; DB will have a column with the name of ``@`!`#`!`12123123`` instead of `@!#!12123123`
- When adding any field with special character[`@user_id`] - Although it's getting stored in DB - It is throwing Unable to find field `@user_id` error with status code `404` instead of the success code with the JSON object of stored field.

---

Originally posted by @bjgajjar at https://github.com/zendframework/zend-db/pull/249#issuecomment-539860084

**Comment by michalbundyra** [comment]
This repository has been moved to laminas/laminas-db. If you feel that this patch is still relevant, please re-open against that repository, and reference this issue. To re-open, we suggest the following workflow:
 - Squash all commits in your branch (`git rebase -i origin/{branch}`)
 - Make a note of all changed files (`git diff --name-only origin/{branch}...HEAD
 - Run the laminas/laminas-migration tool on the code.
 - Clone laminas/laminas-db to another directory.
 - Copy the files from the second bullet point to the clone of laminas/laminas-db.
 - In your clone of laminas/laminas-db, commit the files, push to your fork, and open the new PR.
 We will be providing tooling via laminas/laminas-migration soon to help  automate the process.

---

Originally posted by @weierophinney at https://github.com/zendframework/zend-db/pull/249#issuecomment-570001159

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
