### ISSUE TITLE
DDL improves

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#73]
Hello, guys
I want to add column with options such as AUTO INCREMENT and unsigned. How it do? 
Finally I've created follow class and add Constraint 

`class AutoIncrement extends AbstractConstraint

{
    /**
     * @var string
     */
    protected $specification = 'AUTO_INCREMENT';
}`

Which is better way for creating table with DDL abstraction?

---

Originally posted by @melnychukvitaliy at https://github.com/zendframework/zend-db/issues/246

**Comment by michalbundyra** [comment]
MySQL DDL already supports auto_increment keyword.

```
$column->setOption('AUTO_INCREMENT', true);
```

In general, current API adds column options not by extending constraints, but adding it to a list of keywords for syntax generator in appropriate engine decorator, eg https://github.com/zendframework/zend-db/blob/405e301f877e1b34ccdf5ed71294949000789a40/src/Sql/Platform/Mysql/Ddl/AlterTableDecorator.php#L105

---

Originally posted by @alextech at https://github.com/zendframework/zend-db/issues/246#issuecomment-297169015

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
