### ISSUE TITLE
no error code for statement runtime exception

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#75]
Using Zend\Db\Adapter\Driver\Oci8\Statement as an example, if a runtime error occurs during sql execution (eg duplicate value on insert), the exception's code is populated with a DMBS error code.

Is there any reason not to return a DBMS error code for other drivers (I'm looking at mysqli & pdo)? They are well-defined, and give developers a way of handling different types of runtime exceptions.

---

Originally posted by @brettmc at https://github.com/zendframework/zend-db/issues/243

**Comment by michalbundyra** [comment]
I've started playing with this, and success has been dependent on how DBMS vendors represent exception codes. For example, postgres uses the sql standard [SQLSTATE error codes](https://www.postgresql.org/docs/current/static/errcodes-appendix.html#ERRCODES-TABLE) which are non-numeric, so they don't play well with zend-db's exceptions.
I see that [\PDOException](http://php.net/manual/en/class.pdoexception.php) implements string-based error codes (I assume for this very reason). Does it sound palatable to make exception error codes strings in zend-db ?

---

Originally posted by @brettmc at https://github.com/zendframework/zend-db/issues/243#issuecomment-295249029

**Comment by michalbundyra** [comment]
I've been experiencing the same thing with the IbmDb2 adapter using PHP 7.1. `db2_stmt_error()` returns a string, and Zend\Db\Adapter\Exception expects the second constructor parameter to be an integer. When the second parameter is a string, I get
```
Wrong parameters for Zend\Db\Adapter\Exception\RuntimeException([string $message [, long $code [, Throwable $previous = NULL]]])
```

---

Originally posted by @chukShirley at https://github.com/zendframework/zend-db/issues/243#issuecomment-295682429

**Comment by michalbundyra** [comment]
@chukShirley I could probably write a failing integration test for that to demonstrate a current bug. Can you provide a simple query which would cause a non-integer error code from DB2? (would something like "select * from non_existent_table" do it?)

---

Originally posted by @brettmc at https://github.com/zendframework/zend-db/issues/243#issuecomment-299369989

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
