### ISSUE TITLE
Delegate quoteIdentifier operation to quoteIdentifierChain

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#77]
Clean up identifier quoting.  quoteIdentifierChain was doing the same thing quoteIdentifier was doing but without safety of using predefined escape tokens. In turn, quoteIdentifier was producing same result as quoteIdentifierChain by adding quotes around the token, which can be simplified by immediately converting identifier to array, pass it to identiferChain, and achieve same result.  Overriding is now necessary only if there are really different rules by the engine. Eg. DB2 seems to be doing something very different.

This will help a lot with consistency in DB engines that have multiple identifiers in the path of a database objects. Eg. PostgreSQL always has trouble between choosing identifier vs chain. This can potentially solve a good portion of bad syntax generation for them.

No unit tests added because this is well covered by existing cases; nothing new or different is generated.

---

Originally posted by @alextech at https://github.com/zendframework/zend-db/pull/233

**Comment by michalbundyra** [comment]
@alextech 
> No unit tests added because this is well covered by existing cases; nothing new or different is generated.

Thanks for the hint!


---

Originally posted by @froschdesign at https://github.com/zendframework/zend-db/pull/233#issuecomment-287533338

**Comment by michalbundyra** [comment]
How does that one small sprintf() change lowers unit test coverage across all files?

---

Originally posted by @alextech at https://github.com/zendframework/zend-db/pull/233#issuecomment-287651616

**Comment by michalbundyra** [comment]
@alextech you mentioned that this PR fixes some potential issue in SQL syntax generation. Can we found and example? We need to prove with a unit test that this PR fixes something. Now, we have the same unit test of before and this PR seems not necessary.

---

Originally posted by @ezimuel at https://github.com/zendframework/zend-db/pull/233#issuecomment-349017356

**Comment by michalbundyra** [comment]
@ezimuel pretty much every quoteIdentifier call across the codebase when using PostgreSQL or SQL Server **including userland usage in other libraries and application code** 

https://github.com/zendframework/zend-db/pull/247/files/bfb73c8bf4be5d98207a9911eca14aabdadd79c8#diff-0113773e7838ad267d6360c243edc298R235 
Or https://github.com/zendframework/zend-db/issues/161 (Ignore the sequence part)

Or related random example from other library https://github.com/zendframework/zend-log/issues/63,
some of my DDL PRs...

The reoccurring theme is the need to check database type and if an object path was given **for every** attempt to quote an identifier to decide if `quoteIdentifier` or `quoteIdentifierChain` should be used, both within zend db codebase, **and in application code** using zend db.  Any place where this is forgotten, such as pull request I linked, results in crashes that @xorock brought up in several places. As I was investigating why that is, I noticed how both functions essentially do the same thing with minor difference so I consolidated the usage. The **lack of unit tests in itself proves** that the PR does not break any existing usage; the whole point is to fix this inconsistency that makes *all existing* code work as it did before, while not needing to check database type and existence of path in the future.

For explanation of what I mean by "object path", look last comment in #206 and a typical usage example in the issue description. ( I cannot remember if this PR can fix that issue directly, but its a step towards it, as with it, identifiers can be expressed as an array or if string given, explode on object path delimiter to create needed array, and be able to quote it without having to worry about it being chain or what)

---

Originally posted by @alextech at https://github.com/zendframework/zend-db/pull/233#issuecomment-349063289

**Comment by michalbundyra** [comment]
This repository has been moved to laminas/laminas-db. If you feel that this patch is still relevant, please re-open against that repository, and reference this issue. To re-open, we suggest the following workflow:
 - Squash all commits in your branch (`git rebase -i origin/{branch}`)
 - Make a note of all changed files (`git diff --name-only origin/{branch}...HEAD
 - Run the laminas/laminas-migration tool on the code.
 - Clone laminas/laminas-db to another directory.
 - Copy the files from the second bullet point to the clone of laminas/laminas-db.
 - In your clone of laminas/laminas-db, commit the files, push to your fork, and open the new PR.
 We will be providing tooling via laminas/laminas-migration soon to help  automate the process.

---

Originally posted by @weierophinney at https://github.com/zendframework/zend-db/pull/233#issuecomment-570001164

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
