### ISSUE TITLE
TableIdentifier schema parameter to allow arrays for use in quoteIdentifierChain to express full object path.

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#78]
#206 Allow expression of full path towards table by allowing array as parameter for $schema in TableIdentifier and use `quoteIdentifierChain` in Sql table resolver. Reasoning explained in the issue.

While working on this noticed that `quoteIdentifierChain` tries to preform near identical operation as `identifierChain`, hence the change in the `AbstractSQL` class, but in less safer way. The result is the same most of the time but it uses hardcoded strings, instead of tokens specified in the specification that `quoteIdentifier` is using, such as `quoteIdentiferTo` or `quoteIdentifer[0]` and `getIdentifierSeparator()`.

I think this is an oversight since databases with more complex database object locator rules (PostgreSQL and SQL Server) are only now becoming more popular.  Cleaning that up possibly in another PR.

---

Originally posted by @alextech at https://github.com/zendframework/zend-db/pull/232

**Comment by michalbundyra** [comment]
@alextech 
I think you should deactivate your automated CS corrections.

---

Originally posted by @froschdesign at https://github.com/zendframework/zend-db/pull/232#issuecomment-287534015

**Comment by michalbundyra** [comment]
This repository has been moved to laminas/laminas-db. If you feel that this patch is still relevant, please re-open against that repository, and reference this issue. To re-open, we suggest the following workflow:
 - Squash all commits in your branch (`git rebase -i origin/{branch}`)
 - Make a note of all changed files (`git diff --name-only origin/{branch}...HEAD
 - Run the laminas/laminas-migration tool on the code.
 - Clone laminas/laminas-db to another directory.
 - Copy the files from the second bullet point to the clone of laminas/laminas-db.
 - In your clone of laminas/laminas-db, commit the files, push to your fork, and open the new PR.
 We will be providing tooling via laminas/laminas-migration soon to help  automate the process.

---

Originally posted by @weierophinney at https://github.com/zendframework/zend-db/pull/232#issuecomment-570001166

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
