### ISSUE TITLE
SQL Server ALTER TABLE adding column

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#82]
SQL Server `Ddl\AlterTable` `addColumn` produces

```
 ALTER TABLE [users]
 ADD COLUMN [profile_image] INTEGER
```

Should be

```
ALTER TABLE [users]
ADD [profile_image] INTEGER
```

---

Originally posted by @alextech at https://github.com/zendframework/zend-db/issues/215

**Comment by michalbundyra** [comment]
Add the moment there is no decorator to manipulate the `ALTER TABLE` syntax from the SQL Server.

---

Originally posted by @froschdesign at https://github.com/zendframework/zend-db/issues/215#issuecomment-277472844

**Comment by michalbundyra** [comment]
Yes, I will add it the same way I added decorator for PostgreSQL to fix index bugs. Just felt sad that a platform which is in list of supported ones gives this many syntax errors on basic commands so adding this to my todo list after I finish fixing sequence bugs.

---

Originally posted by @alextech at https://github.com/zendframework/zend-db/issues/215#issuecomment-277473327

**Comment by michalbundyra** [comment]
@alextech
> Just felt sad that a platform which is in list of supported ones...

Where?

---

Originally posted by @froschdesign at https://github.com/zendframework/zend-db/issues/215#issuecomment-277473528

**Comment by michalbundyra** [comment]
@froschdesign 
https://docs.zendframework.com/zend-db/adapter/

>The list of officially supported drivers:
IbmDb2: The ext/ibm_db2 deriver
Mysqli: The ext/mysqli driver
Oci8: The ext/oci8 driver
Pgsql: The ext/pgsql driver
Sqlsrv: The ext/sqlsrv driver (from Microsoft)
Pdo_Mysql: MySQL via the PDO extension
Pdo_Sqlite: SQLite via the PDO extension
Pdo_Pgsql: PostgreSQL via the PDO extension


---

Originally posted by @alextech at https://github.com/zendframework/zend-db/issues/215#issuecomment-277473655

**Comment by michalbundyra** [comment]
@alextech 
Adapter not DDL Abstraction!

> The following platforms have platform specializations for DDL:
>
> * MySQL
> * All databases compatible with ANSI SQL92


https://docs.zendframework.com/zend-db/sql-ddl/

---

Originally posted by @froschdesign at https://github.com/zendframework/zend-db/issues/215#issuecomment-277473846

**Comment by michalbundyra** [comment]
@froschdesign 
Support for driver does not imply support across the whole package? That is unexpected, but OK, point taken. In that case, last 3 issues, and probably many more undiscovered ones, do not need fixing that much, can be closed, since according to that other link its not officially supported and effort taken to add full support may not be worth it, unless you disagree.

---

Originally posted by @alextech at https://github.com/zendframework/zend-db/issues/215#issuecomment-277474370

**Comment by michalbundyra** [comment]
The priority is not very high for the DDL Abstraction. (imo)

---

Originally posted by @froschdesign at https://github.com/zendframework/zend-db/issues/215#issuecomment-277478217

**Comment by michalbundyra** [comment]
That is fine.

---

Originally posted by @alextech at https://github.com/zendframework/zend-db/issues/215#issuecomment-277478350

**Comment by michalbundyra** [comment]
@froschdesign we are already supporting DDL for specific platform like SQL Server, see [here](https://github.com/zendframework/zend-db/tree/master/src/Sql/Platform/SqlServer/Ddl). 
The documentation should be updated https://docs.zendframework.com/zend-db/sql-ddl/.
That said, I would love to see a PR from @alextech with a decorator for AlterTable on SqlServer.

---

Originally posted by @ezimuel at https://github.com/zendframework/zend-db/issues/215#issuecomment-281412424

**Comment by michalbundyra** [comment]
@ezimuel I am on it! Thank you for motivation. Even though I was mostly focused on sequences, not being able to set up migrations to support testing of higher-level featured due to these API limitations was a significant annoyance so this distraction will help.

Question about workflow. You assigned it to yourself so does that mean you are working on it or you are willing to review what I will submit? I do not want to cause extra difficulties for you submitting conflicting PRs.

---

Originally posted by @alextech at https://github.com/zendframework/zend-db/issues/215#issuecomment-281415662

**Comment by michalbundyra** [comment]
@alextech I assigned to myself so I remember to manage it. Please, work on the PR and I'll review it, and thanks in advance for your contribution!

---

Originally posted by @ezimuel at https://github.com/zendframework/zend-db/issues/215#issuecomment-281416912

**Comment by michalbundyra** [comment]
@ezimuel 
> we are already supporting DDL for specific platform like SQL Server

Right, but not for the `ALTER TABLE` syntax. 😉 

---

Originally posted by @froschdesign at https://github.com/zendframework/zend-db/issues/215#issuecomment-281420722

**Comment by michalbundyra** [comment]
@froschdesign right, but we can add it.

---

Originally posted by @ezimuel at https://github.com/zendframework/zend-db/issues/215#issuecomment-281422365

**Comment by michalbundyra** [comment]
yes because we already have high profile public developers saying things like https://twitter.com/DragonBe/status/832182873977413632
because they saw PR for vagrant and such. So it looks like the whole thing is ready. Public will try to follow the post and run it, get nice crashes, and then say bad words.

---

Originally posted by @alextech at https://github.com/zendframework/zend-db/issues/215#issuecomment-281423816

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
