### ISSUE TITLE
SQL Server IDENTITY support

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#83]
`SqlServer\Ddl\CreatTableDecorator` does not know how to process `$id->setOption('IDENTITY', '1, 1');` , equivalent to AUTO_INCREMENT from MySQL or SEQUENCE from PostgreSQL

---

Originally posted by @alextech at https://github.com/zendframework/zend-db/issues/214

**Comment by michalbundyra** [comment]
@alextech can you provide a working example? Thanks!

---

Originally posted by @ezimuel at https://github.com/zendframework/zend-db/issues/214#issuecomment-281988263

**Comment by michalbundyra** [comment]
Sorry, abused this as personal todo list:

```
public function testOptions() {
        $ctd = new CreateTableDecorator();

        $ct = new CreateTable('foo');
        $ctd->setSubject($ct);

        $col = new Column('id');
        $col->setOption('IDENTITY', '1,1');
        $ct->addColumn($col);

        $this->assertEquals(
            "CREATE TABLE [foo] ( \n    [id] INTEGER NOT NULL IDENTITY(1, 1) \n)",
            $ctd->getSqlString(new SqlServer())
        );
    }
```
Can paste to `SqlServer\Ddl\CreateTableDecoratorTest`. 

---

Originally posted by @alextech at https://github.com/zendframework/zend-db/issues/214#issuecomment-282001643

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
