### ISSUE TITLE
SQL Abstraction, Select API

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#93]
In the Select section, API description, replace

```
public function join(string|array $name, string $on, string|array $columns = self::SQL_STAR, string $type = self::JOIN_INNER) : self;
```

by 

```
public function join(string|array $name, string|Zend\Db\Sql\ExpressionInterface $on, string|array $columns = self::SQL_STAR, string $type = self::JOIN_INNER) : self;
```

---

Originally posted by @dafap at https://github.com/zendframework/zend-db/issues/176

**Comment by michalbundyra** [comment]
@dafap I see `$on` is string in the source code. Can you give an example of `$on` accepting `Zend\Db\Sql\ExpressionInterface`? Thanks.

---

Originally posted by @ezimuel at https://github.com/zendframework/zend-db/issues/176#issuecomment-295866441

**Comment by michalbundyra** [comment]
This is possible using the ON clause as a ExpressionInterface :

```
$on = new Literal('browser_stats_daily.user_agent LIKE user_agents.user_agent');
$select = $this->tableGateway->getSql()->select();
$select->quantifier(Select::QUANTIFIER_DISTINCT)
       ->columns(["user_agent"])
       ->join("browser_stats_daily", $on, Select::SQL_STAR, Select::JOIN_RIGHT)
       ->where->isNotNull("user_agents.user_agent");
```

---

Originally posted by @dafap at https://github.com/zendframework/zend-db/issues/176#issuecomment-296352325

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
