### ISSUE TITLE
Metadata\Source\Factory throws specific exception

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#95]
Metadata\Source\Factory throws specific exception when the platform is not supported.

It will help to catch this specific exception in zf-apigility-admin,
matching exception by text is too fragile.

https://github.com/zfcampus/zf-apigility-admin/pull/365/files

---

Originally posted by @Naktibalda at https://github.com/zendframework/zend-db/pull/170

**Comment by michalbundyra** [comment]
Your changes have failed the coding standards check.  Please refer to CONTRIBUTING.md for details on how to run php-cs-fixer on your changes to ensure they conform.  


---

Originally posted by @adamlundrigan at https://github.com/zendframework/zend-db/pull/170#issuecomment-250982615

**Comment by michalbundyra** [comment]
Done


---

Originally posted by @Naktibalda at https://github.com/zendframework/zend-db/pull/170#issuecomment-250983440

**Comment by michalbundyra** [comment]
Would it be better to rename `InvalidArgumentException` to `UnknownPlatformException extends InvalidArgumentException`


---

Originally posted by @Naktibalda at https://github.com/zendframework/zend-db/pull/170#issuecomment-259384339

**Comment by michalbundyra** [comment]
@Naktibalda I'm planning to merge this PR for zend-db 3.0.0. It's ok using InvalidArgumentException as you did in the PR. We don't need a specific UnknownPlatformException becuase now we have a better namespace.
Can you send this PR against develop? Thanks!

---

Originally posted by @ezimuel at https://github.com/zendframework/zend-db/pull/170#issuecomment-285055596

**Comment by michalbundyra** [comment]
I changed the base branch, but I don't understand what you mean with "a better namespace", do I need to change anything in the code?

---

Originally posted by @Naktibalda at https://github.com/zendframework/zend-db/pull/170#issuecomment-285794975

**Comment by michalbundyra** [comment]
This repository has been moved to laminas/laminas-db. If you feel that this patch is still relevant, please re-open against that repository, and reference this issue. To re-open, we suggest the following workflow:
 - Squash all commits in your branch (`git rebase -i origin/{branch}`)
 - Make a note of all changed files (`git diff --name-only origin/{branch}...HEAD
 - Run the laminas/laminas-migration tool on the code.
 - Clone laminas/laminas-db to another directory.
 - Copy the files from the second bullet point to the clone of laminas/laminas-db.
 - In your clone of laminas/laminas-db, commit the files, push to your fork, and open the new PR.
 We will be providing tooling via laminas/laminas-migration soon to help  automate the process.

---

Originally posted by @michalbundyra at https://github.com/zendframework/zend-db/pull/170#issuecomment-575304347

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html)
